## Set up and Imports

In [12]:
import os
import torch
import numpy as np
import pandas as pd
from datasets import load_dataset, Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import roc_auc_score, precision_recall_curve, auc, roc_curve
from google.colab import drive
from sklearn.model_selection import train_test_split
import torch
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.covariance import EmpiricalCovariance
from transformers import DataCollatorWithPadding
import torch.nn.functional as F
from sklearn.manifold import TSNE
import plotly.express as px
import plotly.io as pio
pio.renderers.default = 'colab'
from IPython.display import display
from captum.attr import LayerIntegratedGradients

In [13]:
pip install captum

Requirement already satisfied: captum in /usr/local/lib/python3.12/dist-packages (0.9.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from captum) (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from captum) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from captum) (26.2)
Requirement already satisfied: torch>=2.3 in /usr/local/lib/python3.12/dist-packages (from captum) (2.11.0+cu128)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from captum) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.3->captum) (3.29.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3->captum) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3->captum) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3->captum) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3->captum) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3->captum) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3->captum) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.3->captum) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3->captum) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3->captum) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3->captum) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3->captum) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3->captum) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3->captum) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.3->captum) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.3->captum) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.3->captum) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.3->captum) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.3->captum) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.3->captum) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.3->captum) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.3->captum) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.3->captum) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.3->captum) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.3->captum) (12.8.90)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->captum) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->captum) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->captum) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->captum) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->captum) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->captum) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->captum) (2.9.0.post0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=2.3->captum) (1.5.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->captum) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.3->captum) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.3->captum) (3.0.3)

In [14]:
pip install --upgrade datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.17.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (3.14.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.0)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)

In [28]:
drive.mount('/content/drive')
SAVE_PATH = "/content/drive/MyDrive/SNIPS_OOD_Project"
if not os.path.exists(SAVE_PATH):
    os.makedirs(SAVE_PATH)

MODEL_NAME = "bert-base-uncased"
NUM_FOLDS = 5
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Metryki ODD

In [16]:
def compute_ood_metrics(logits, labels, ood_label_idx):
    probs = torch.nn.functional.softmax(torch.tensor(logits), dim=-1).numpy()
    ood_scores = probs[:, ood_label_idx]
    y_true = (labels == ood_label_idx).astype(int)

    # AUROC
    auroc = roc_auc_score(y_true, ood_scores)
    # AUPR
    precision, recall, _ = precision_recall_curve(y_true, ood_scores)
    aupr = auc(recall, precision)
    # FPR95
    idx = np.argmin(np.abs(recall - 0.95))
    fpr95 = 1 - precision[idx]

    return auroc, aupr, fpr95

## SNIPS dataset

In [17]:
print("--- Pobieranie zbioru SNIPS (7 klas) ---")
raw_ds = load_dataset("DeepPavlov/snips", "default")
train_df = pd.DataFrame(raw_ds['train'])
test_df = pd.DataFrame(raw_ds['test'])
snips_df = pd.concat([train_df, test_df], ignore_index=True) # Zawiera klasy 0-6

possible_text_cols = ['query', 'utterance', 'text', 'sentence']
for col in possible_text_cols:
    if col in snips_df.columns:
        snips_df = snips_df.rename(columns={col: 'text'})
        break

--- Pobieranie zbioru SNIPS (7 klas) ---

## Tokenizer and embeddings

In [18]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

def tokenize_fn(batch):
    return tokenizer(
        batch["text"],
        padding=True,
        truncation=True,
        max_length=64   # (SNIPS nie potrzebuje 512)
    )

In [19]:
def get_embeddings(model, dataset, batch_size=32):
    model.eval()
    model.to(device)

    loader = torch.utils.data.DataLoader(
        dataset,
        batch_size=batch_size,
        collate_fn=data_collator
    )
    embs = []

    with torch.no_grad():
        for batch in loader:
            batch = {k: v.to(device) for k, v in batch.items()}

            outputs = model(**batch)

            embs.append(outputs.logits.detach().cpu().numpy())

    return np.concatenate(embs)

## Contrastive trainer

In [20]:
class ContrastiveTrainer(Trainer):
    def __init__(self, *args, lambda_param=2.0, **kwargs):
        """
        lambda_param: Waga dla straty kontrastywnej (w artykule domyślnie używają 2.0)
        """
        super().__init__(*args, **kwargs)
        self.lambda_param = lambda_param

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        inputs["output_hidden_states"] = True

        outputs = model(**inputs)

        loss_ce = outputs.loss

        hidden_states = outputs.hidden_states[-1]
        h = hidden_states[:, 0, :]

        labels = inputs.get("labels")

        batch_size = labels.size(0)
        d = h.size(1) # wymiar ukryty (dla BERTa 768)

        dist_matrix = torch.cdist(h, h, p=2) ** 2

        pos_mask = (labels.unsqueeze(0) == labels.unsqueeze(1))
        neg_mask = ~pos_mask

        pos_mask.fill_diagonal_(False)

        pos_counts = torch.clamp(pos_mask.sum(dim=1).float(), min=1.0)
        neg_counts = torch.clamp(neg_mask.sum(dim=1).float(), min=1.0)

        xi = (dist_matrix * pos_mask).max()

        l_pos = (dist_matrix * pos_mask).sum(dim=1) / pos_counts

        l_neg = (F.relu(xi - dist_matrix) * neg_mask).sum(dim=1) / neg_counts

        loss_margin = (l_pos.sum() + l_neg.sum()) / (d * batch_size)

        loss = loss_ce + self.lambda_param * loss_margin

        return (loss, outputs) if return_outputs else loss

## XAI Helper functions

In [21]:
def mahalanobis_ood_score(input_ids_batch, attention_mask_batch):
    outputs = model(input_ids=input_ids_batch, attention_mask=attention_mask_batch)
    embeddings = outputs.logits

    diff = embeddings.unsqueeze(1) - class_means_tensor.unsqueeze(0)

    left_term = torch.matmul(diff, inv_cov_tensor)

    dist_sq = torch.sum(left_term * diff, dim=-1)

    min_dist_sq, _ = torch.min(dist_sq, dim=1)

    return min_dist_sq


def r_angle_ood_score(input_ids_batch, attention_mask_batch):
    outputs = model(input_ids=input_ids_batch, attention_mask=attention_mask_batch)

    embeddings = outputs.logits

    embeddings_norm = F.normalize(embeddings, p=2, dim=1)
    centroids_norm = F.normalize(class_means_tensor, p=2, dim=1)
    cos_sims = torch.matmul(embeddings_norm, centroids_norm.T)

    max_cos_sim, _ = torch.max(cos_sims, dim=1)
    return 1.0 - max_cos_sim

## Cross-validation

In [22]:
FOLDS_CONFIG = [
    {"ood": [5, 6], "name": "Kino"},
    {"ood": [3, 0], "name": "Muzyka"},
    {"ood": [2, 1], "name": "Usługi"},
    {"ood": [4, 5], "name": "Twórczość"},
    {"ood": [6, 1], "name": "Mieszany"}
]

## Główna pętla - MAHALANOBIS

In [24]:
results_MAHALANOBIS = []
xai_lto_mahalanobis = []

for fold_idx, config in enumerate(FOLDS_CONFIG):
    print(f"\n===== FOLD {fold_idx+1}: {config['name']} =====")

    ood_classes = config["ood"]
    id_classes = [c for c in range(7) if c not in ood_classes]

    id_df_full = snips_df[snips_df['label'].isin(id_classes)].copy()
    ood_df_full = snips_df[snips_df['label'].isin(ood_classes)].copy()

    train_id, test_id = train_test_split(
        id_df_full, test_size=0.2, stratify=id_df_full['label'], random_state=42
    )

    train_df_fold = train_id.copy()

    test_df_fold = pd.concat([test_id, ood_df_full]).sample(frac=1, random_state=42)

    mapping = {old_id: new_id for new_id, old_id in enumerate(id_classes)}

    train_df_fold["mapped_label"] = train_df_fold["label"].map(mapping)

    train_df_fold = train_df_fold.dropna(subset=["mapped_label"])
    train_df_fold["mapped_label"] = train_df_fold["mapped_label"].astype(int)

    train_ds = Dataset.from_pandas(
        train_df_fold[['text', 'mapped_label']].rename(columns={'mapped_label': 'label'})
    ).map(tokenize_fn, batched=True)

    test_ds = Dataset.from_pandas(test_df_fold).map(tokenize_fn, batched=True)

    train_ds = train_ds.remove_columns([col for col in train_ds.column_names if col not in ["input_ids", "attention_mask", "label"]])
    test_ds = test_ds.remove_columns([col for col in test_ds.column_names if col not in ["input_ids", "attention_mask"]])

    train_ds.set_format(type='torch')
    test_ds.set_format(type='torch')

    # model
    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=len(id_classes)
    )

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    training_args = TrainingArguments(
        output_dir="./tmp",
        num_train_epochs=3,
        per_device_train_batch_size=32,
        eval_strategy="no",
        save_strategy="no",
        logging_steps=100,
        report_to="none",
        fp16=True
    )

    trainer = ContrastiveTrainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        data_collator=data_collator,
        lambda_param=2.0 # Waga z artykułu
    )
    trainer.train()

    train_embeddings = get_embeddings(model, train_ds)
    test_embeddings = get_embeddings(model, test_ds)

    train_labels = train_df_fold['mapped_label'].values
    true_labels = test_df_fold['label'].values

    class_means = []
    for c in range(len(id_classes)):
        class_means.append(train_embeddings[train_labels == c].mean(axis=0))
    class_means = np.array(class_means)

    cov = EmpiricalCovariance().fit(train_embeddings)
    precision = cov.precision_

    def mahalanobis(x, mean):
        diff = x - mean
        return np.sqrt(diff @ precision @ diff.T)

    scores = []
    diff = test_embeddings[:, None, :] - class_means[None, :, :]
    scores = np.einsum('bij,jk,bik->bi', diff, precision, diff)
    scores = np.sqrt(scores).min(axis=1)

    scores = np.array(scores)

    y_true = np.array([1 if l in ood_classes else 0 for l in true_labels])

    auroc = roc_auc_score(y_true, scores)
    precision_arr, recall_arr, _ = precision_recall_curve(y_true, scores)
    aupr = auc(recall_arr, precision_arr)

    fpr, tpr, thresholds = roc_curve(y_true, scores)
    idx_95 = np.argmin(np.abs(tpr - 0.95))
    fpr95 = fpr[idx_95]

    print(f"AUROC: {auroc:.4f}")

    # print(f"Generowanie wykresu t-SNE dla Foldu {fold_idx+1}...")

    # X_fold = test_embeddings

    # y_fold_names = []
    # for label in true_labels:
    #     if label in ood_classes:
    #         y_fold_names.append(f"OOD (Klasa {label})")
    #     else:
    #         y_fold_names.append(f"ID (Klasa {label})")

    # tsne = TSNE(n_components=2, random_state=42, init='pca', learning_rate='auto')
    # projections = tsne.fit_transform(X_fold)

    # fig = px.scatter(
    #     x=projections[:, 0],
    #     y=projections[:, 1],
    #     color=y_fold_names,
    #     title=f"Przestrzeń ukryta BERT - Fold {fold_idx+1}: {config['name']} (Zb. Testowy)",
    #     labels={'color': 'Rodzaj intencji', 'x': 'Wymiar 1', 'y': 'Wymiar 2'},
    #     opacity=0.8
    # )

    # fig.update_traces(marker=dict(size=4))

    # html_path = f"{SAVE_PATH}/mahalanobis_tsne_fold_{fold_idx+1}.html"
    # fig.write_html(html_path)
    # print(f"✅ Zapisano wykres: {html_path}")

    results_MAHALANOBIS.append({
        "fold": fold_idx+1,
        "scenario": config['name'],
        "auroc": auroc,
        "aupr": aupr,
        "fpr95": fpr95
    })

    print(f"--- Generowanie XAI dla Foldu {fold_idx + 1} ---")

    class_means_tensor = torch.tensor(class_means, dtype=torch.float32).to(device)
    inv_cov_tensor = torch.tensor(precision, dtype=torch.float32).to(device)

    lig = LayerIntegratedGradients(mahalanobis_ood_score, model.get_input_embeddings())

    top_5_indices = np.argsort(scores)[::-1][:5]
    special_tokens = tokenizer.all_special_tokens

    for rank, idx in enumerate(top_5_indices, 1):
        sample_text = test_df_fold.iloc[idx]['text']
        score = scores[idx]

        inputs = tokenizer(sample_text, return_tensors="pt", truncation=True, padding=True)
        input_ids_pt = inputs["input_ids"].to(device)
        attention_mask_pt = inputs["attention_mask"].to(device)

        attributions = lig.attribute(
            inputs=input_ids_pt, target=None, additional_forward_args=(attention_mask_pt,)
        )

        attributions_sum = attributions.sum(dim=-1).squeeze(0).cpu().detach().numpy()
        tokens = tokenizer.convert_ids_to_tokens(input_ids_pt[0])

        word_attributions = [
            (tok.replace('Ġ', '').replace('##', ''), attr)
            for tok, attr in zip(tokens, attributions_sum) if tok not in special_tokens
        ]

        top_tokens = sorted([attr for attr in word_attributions if attr[1] > 0], key=lambda x: x[1], reverse=True)[:3]

        t1, w1 = top_tokens[0] if len(top_tokens) > 0 else (None, 0.0)
        t2, w2 = top_tokens[1] if len(top_tokens) > 1 else (None, 0.0)
        t3, w3 = top_tokens[2] if len(top_tokens) > 2 else (None, 0.0)

        print(f"[Top {rank}] Mahalanobis: {score:.4f} | Tekst: {sample_text}")
        print(f"Triggery: 1. {t1}({w1:.3f}) | 2. {t2}({w2:.3f}) | 3. {t3}({w3:.3f})")

        xai_lto_mahalanobis.append({
            "fold": fold_idx + 1,
            "scenario": config["name"],
            "rank_in_fold": rank,
            "text": sample_text,
            "score": score,
            "trigger_1_token": t1,
            "trigger_1_weight": float(w1) if t1 else 0.0,
            "trigger_2_token": t2,
            "trigger_2_weight": float(w2) if t2 else 0.0,
            "trigger_3_token": t3,
            "trigger_3_weight": float(w3) if t3 else 0.0
        })
xai_df = pd.DataFrame(xai_lto_mahalanobis)
xai_df.to_csv("xai/contrastive_xai_lto_mahalanobis.csv", index=False)

===== FOLD 1: Kino =====

Map:   0%|          | 0/8296 [00:00<?, ? examples/s]

Map:   0%|          | 0/6188 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.9374
--- Generowanie XAI dla Foldu 1 ---
[Top 1] Mahalanobis: 29.7204 | Tekst: when is Red Shirts showing at Dickinson Theatres
Triggery: 1. theatres(713.201) | 2. shirts(490.140) | 3. red(185.043)
[Top 2] Mahalanobis: 27.5886 | Tekst: When is Youth Without Youth being shown at the nearest movie house ?
Triggery: 1. is(322.355) | 2. ?(250.542) | 3. being(207.256)
[Top 3] Mahalanobis: 27.3907 | Tekst: What is the nearest cinema showing Love in Mandya ?
Triggery: 1. cinema(219.357) | 2. nearest(132.989) | 3. what(122.862)
[Top 4] Mahalanobis: 26.3411 | Tekst: Is The Country Doctor on the schedule at any theater near me?
Triggery: 1. theater(608.415) | 2. doctor(497.467) | 3. at(334.675)
[Top 5] Mahalanobis: 26.3407 | Tekst: What movies are at Malco Theatres
Triggery: 1. what(403.619) | 2. at(252.146) | 3. co(118.453)

===== FOLD 2: Muzyka =====

Map:   0%|          | 0/8273 [00:00<?, ? examples/s]

Map:   0%|          | 0/6211 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.7151
--- Generowanie XAI dla Foldu 2 ---
[Top 1] Mahalanobis: 24.5519 | Tekst: Add viktor merjanov to california rock state
Triggery: 1. state(293.122) | 2. to(104.479) | 3. add(103.825)
[Top 2] Mahalanobis: 19.3531 | Tekst: play a top twenty symphony of 2010
Triggery: 1. 2010(236.686) | 2. play(210.346) | 3. top(80.271)
[Top 3] Mahalanobis: 17.1308 | Tekst: Can ten green bottles be added to brooklyn beat ?
Triggery: 1. bottles(129.292) | 2. ten(101.666) | 3. ?(60.260)
[Top 4] Mahalanobis: 14.3019 | Tekst: add Stephen McNally to Confidence Boost
Triggery: 1. boost(124.482) | 2. to(35.752) | 3. confidence(31.831)
[Top 5] Mahalanobis: 13.9295 | Tekst: Show me when and where I can see Song of Summer
Triggery: 1. when(145.480) | 2. where(136.412) | 3. and(90.128)

===== FOLD 3: Usługi =====

Map:   0%|          | 0/8248 [00:00<?, ? examples/s]

Map:   0%|          | 0/6236 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.7830
--- Generowanie XAI dla Foldu 3 ---
[Top 1] Mahalanobis: 13.9367 | Tekst: Is it chillier in Hong Kong than it is here
Triggery: 1. ier(34.236) | 2. hong(31.809) | 3. here(28.539)
[Top 2] Mahalanobis: 13.8045 | Tekst: I want to reserve a gastropub that has a spa .
Triggery: 1. reserve(44.254) | 2. spa(23.459) | 3. want(23.238)
[Top 3] Mahalanobis: 11.7408 | Tekst: Will it get foggy in Spring Hill ?
Triggery: 1. hill(28.650) | 2. it(27.457) | 3. spring(23.838)
[Top 4] Mahalanobis: 11.6081 | Tekst: Is it better in Holi or here
Triggery: 1. li(37.826) | 2. in(27.852) | 3. it(14.823)
[Top 5] Mahalanobis: 11.0960 | Tekst: Will it get chillier in Furano-Ashibetsu Prefectural Natural Park ?
Triggery: 1. tsu(27.714) | 2. prefect(19.358) | 3. ier(11.553)

===== FOLD 4: Twórczość =====

Map:   0%|          | 0/8299 [00:00<?, ? examples/s]

Map:   0%|          | 0/6185 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.8479
--- Generowanie XAI dla Foldu 4 ---
[Top 1] Mahalanobis: 28.5801 | Tekst: give Life A Natural History of the First Four Billion Years of Life on Earth 1 points out of 6
Triggery: 1. 6(62.062) | 2. out(57.247) | 3. history(43.858)
[Top 2] Mahalanobis: 25.6315 | Tekst: is there a Chinese Wikipedia
Triggery: 1. there(348.184) | 2. wikipedia(293.207) | 3. chinese(178.421)
[Top 3] Mahalanobis: 24.9798 | Tekst: Rate Of the Subcontract a 0
Triggery: 1. rate(332.442) | 2. sub(219.769) | 3. tra(115.365)
[Top 4] Mahalanobis: 24.5485 | Tekst: I want Sugarfoot
Triggery: 1. want(603.266) | 2. sugar(465.964) | 3. None(0.000)
[Top 5] Mahalanobis: 24.3204 | Tekst: I need a novel about Polymer Chemistry .
Triggery: 1. polymer(314.299) | 2. chemistry(267.806) | 3. .(207.136)

===== FOLD 5: Mieszany =====

Map:   0%|          | 0/8281 [00:00<?, ? examples/s]

Map:   0%|          | 0/6203 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.8139
--- Generowanie XAI dla Foldu 5 ---
[Top 1] Mahalanobis: 14.2295 | Tekst: nancy, elma ruiz and molly want to eat at a restaurant in Gibraltar
Triggery: 1. restaurant(64.403) | 2. eat(46.100) | 3. gibraltar(37.349)
[Top 2] Mahalanobis: 14.1778 | Tekst: Make me a reservation at Illinois Central Railroad Freight Depot in Singapore with vickie rodriguez, lila reyes and ruby
Triggery: 1. vicki(35.506) | 2. make(30.773) | 3. a(28.207)
[Top 3] Mahalanobis: 13.7049 | Tekst: Would like a table right now for leonor mendoza, imogene and lisa sanchez
Triggery: 1. sanchez(39.104) | 2. table(36.825) | 3. right(21.410)
[Top 4] Mahalanobis: 13.4912 | Tekst: I'd like to watch Sherlock Holmes à New York at KB Theatres
Triggery: 1. theatres(106.217) | 2. kb(67.491) | 3. watch(15.478)
[Top 5] Mahalanobis: 13.3234 | Tekst: book me a restaurant that serves green bean casserole for five people
Triggery: 1. serves(45.858) | 2. people(33.222) | 3. me(26.491)

## Leave One Out - Mahalanobis

In [25]:
results_LOO_MAHALANOBIS = []
xai_loo_mahalanobis = []

for fold_idx in range(7):
    print(f"\n===== FOLD {fold_idx+1} =====")

    ood_classes = [fold_idx]
    id_classes = [c for c in range(7) if c not in ood_classes]

    id_df_full = snips_df[snips_df['label'].isin(id_classes)].copy()
    ood_df_full = snips_df[snips_df['label'].isin(ood_classes)].copy()

    train_id, test_id = train_test_split(
        id_df_full, test_size=0.2, stratify=id_df_full['label'], random_state=42
    )

    train_df_fold = train_id.copy()

    test_df_fold = pd.concat([test_id, ood_df_full]).sample(frac=1, random_state=42)

    mapping = {old_id: new_id for new_id, old_id in enumerate(id_classes)}

    train_df_fold["mapped_label"] = train_df_fold["label"].map(mapping)

    train_df_fold = train_df_fold.dropna(subset=["mapped_label"])
    train_df_fold["mapped_label"] = train_df_fold["mapped_label"].astype(int)

    train_ds = Dataset.from_pandas(
        train_df_fold[['text', 'mapped_label']].rename(columns={'mapped_label': 'label'})
    ).map(tokenize_fn, batched=True)

    test_ds = Dataset.from_pandas(test_df_fold).map(tokenize_fn, batched=True)

    train_ds = train_ds.remove_columns([col for col in train_ds.column_names if col not in ["input_ids", "attention_mask", "label"]])
    test_ds = test_ds.remove_columns([col for col in test_ds.column_names if col not in ["input_ids", "attention_mask"]])

    train_ds.set_format(type='torch')
    test_ds.set_format(type='torch')

    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=len(id_classes)
    )

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    training_args = TrainingArguments(
        output_dir="./tmp",
        num_train_epochs=3,
        per_device_train_batch_size=32,
        eval_strategy="no",
        save_strategy="no",
        logging_steps=100,
        report_to="none",
        fp16=True
    )

    trainer = ContrastiveTrainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        data_collator=data_collator,
        lambda_param=2.0 # Waga z artykułu
    )
    trainer.train()

    train_embeddings = get_embeddings(model, train_ds)
    test_embeddings = get_embeddings(model, test_ds)

    train_labels = train_df_fold['mapped_label'].values
    true_labels = test_df_fold['label'].values

    class_means = []
    for c in range(len(id_classes)):
        class_means.append(train_embeddings[train_labels == c].mean(axis=0))
    class_means = np.array(class_means)

    cov = EmpiricalCovariance().fit(train_embeddings)
    precision = cov.precision_

    def mahalanobis(x, mean):
        diff = x - mean
        return np.sqrt(diff @ precision @ diff.T)

    scores = []
    diff = test_embeddings[:, None, :] - class_means[None, :, :]
    scores = np.einsum('bij,jk,bik->bi', diff, precision, diff)
    scores = np.sqrt(scores).min(axis=1)

    scores = np.array(scores)

    y_true = np.array([1 if l in ood_classes else 0 for l in true_labels])

    auroc = roc_auc_score(y_true, scores)
    precision_arr, recall_arr, _ = precision_recall_curve(y_true, scores)
    aupr = auc(recall_arr, precision_arr)

    fpr, tpr, thresholds = roc_curve(y_true, scores)
    idx_95 = np.argmin(np.abs(tpr - 0.95))
    fpr95 = fpr[idx_95]

    print(f"AUROC: {auroc:.4f}")

    # print(f"Generowanie wykresu t-SNE dla Foldu {fold_idx+1}...")

    # X_fold = test_embeddings

    # y_fold_names = []
    # for label in true_labels:
    #     if label in ood_classes:
    #         y_fold_names.append(f"OOD (Klasa {label})")
    #     else:
    #         y_fold_names.append(f"ID (Klasa {label})")

    # tsne = TSNE(n_components=2, random_state=42, init='pca', learning_rate='auto')
    # projections = tsne.fit_transform(X_fold)

    # fig = px.scatter(
    #     x=projections[:, 0],
    #     y=projections[:, 1],
    #     color=y_fold_names,
    #     title=f"Przestrzeń ukryta BERT - Fold {fold_idx+1} (Zb. Testowy)",
    #     labels={'color': 'Rodzaj intencji', 'x': 'Wymiar 1', 'y': 'Wymiar 2'},
    #     opacity=0.8
    # )

    # fig.update_traces(marker=dict(size=4))

    # html_path = f"{SAVE_PATH}/mahalanobis_loo_tsne_fold_{fold_idx+1}.html"
    # fig.write_html(html_path)
    # print(f"✅ Zapisano wykres: {html_path}")

    results_LOO_MAHALANOBIS.append({
        "fold": fold_idx+1,
        "scenario": f"OOD_Class_{fold_idx+1}",
        "auroc": auroc,
        "aupr": aupr,
        "fpr95": fpr95
    })

    print(f"--- Generowanie XAI dla Foldu {fold_idx + 1} ---")

    class_means_tensor = torch.tensor(class_means, dtype=torch.float32).to(device)
    inv_cov_tensor = torch.tensor(precision, dtype=torch.float32).to(device)

    lig = LayerIntegratedGradients(mahalanobis_ood_score, model.get_input_embeddings())

    top_5_indices = np.argsort(scores)[::-1][:5]
    special_tokens = tokenizer.all_special_tokens

    for rank, idx in enumerate(top_5_indices, 1):
        sample_text = test_df_fold.iloc[idx]['text']
        score = scores[idx]

        inputs = tokenizer(sample_text, return_tensors="pt", truncation=True, padding=True)
        input_ids_pt = inputs["input_ids"].to(device)
        attention_mask_pt = inputs["attention_mask"].to(device)

        attributions = lig.attribute(
            inputs=input_ids_pt, target=None, additional_forward_args=(attention_mask_pt,)
        )

        attributions_sum = attributions.sum(dim=-1).squeeze(0).cpu().detach().numpy()
        tokens = tokenizer.convert_ids_to_tokens(input_ids_pt[0])

        word_attributions = [
            (tok.replace('Ġ', '').replace('##', ''), attr)
            for tok, attr in zip(tokens, attributions_sum) if tok not in special_tokens
        ]

        top_tokens = sorted([attr for attr in word_attributions if attr[1] > 0], key=lambda x: x[1], reverse=True)[:3]

        t1, w1 = top_tokens[0] if len(top_tokens) > 0 else (None, 0.0)
        t2, w2 = top_tokens[1] if len(top_tokens) > 1 else (None, 0.0)
        t3, w3 = top_tokens[2] if len(top_tokens) > 2 else (None, 0.0)

        print(f"[Top {rank}] Mahalanobis: {score:.4f} | Tekst: {sample_text}")
        print(f"Triggery: 1. {t1}({w1:.3f}) | 2. {t2}({w2:.3f}) | 3. {t3}({w3:.3f})")

        xai_loo_mahalanobis.append({
            "fold": fold_idx + 1,
            "scenario": f"OOD_Class_{fold_idx+1}",
            "rank_in_fold": rank,
            "text": sample_text,
            "score": score,
            "trigger_1_token": t1,
            "trigger_1_weight": float(w1) if t1 else 0.0,
            "trigger_2_token": t2,
            "trigger_2_weight": float(w2) if t2 else 0.0,
            "trigger_3_token": t3,
            "trigger_3_weight": float(w3) if t3 else 0.0
        })
xai_df = pd.DataFrame(xai_loo_mahalanobis)
xai_df.to_csv("xai/contrastive_xai_loo_mahalanobis.csv", index=False)

===== FOLD 1 =====

Map:   0%|          | 0/9953 [00:00<?, ? examples/s]

Map:   0%|          | 0/4531 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.6230
--- Generowanie XAI dla Foldu 1 ---
[Top 1] Mahalanobis: 19.2380 | Tekst: add I’m Only a Man to my flow español
Triggery: 1. m(95.714) | 2. i(81.723) | 3. only(61.743)
[Top 2] Mahalanobis: 18.9221 | Tekst: Add I Hate Myself and I Want to Die to my Six string peacefulness
Triggery: 1. die(65.248) | 2. add(62.134) | 3. six(54.377)
[Top 3] Mahalanobis: 17.8489 | Tekst: add Paul Franklin to my The Bachelor Party
Triggery: 1. party(83.142) | 2. bachelor(45.867) | 3. my(44.451)
[Top 4] Mahalanobis: 17.6923 | Tekst: add Deus Deceptor to Dance Workout
Triggery: 1. workout(71.428) | 2. ept(52.399) | 3. de(43.250)
[Top 5] Mahalanobis: 17.1632 | Tekst: add sonntag to my Assassin's Creed
Triggery: 1. son(85.420) | 2. g(75.295) | 3. s(67.871)

===== FOLD 2 =====

Map:   0%|          | 0/9928 [00:00<?, ? examples/s]

Map:   0%|          | 0/4556 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.8937
--- Generowanie XAI dla Foldu 2 ---
[Top 1] Mahalanobis: 22.4305 | Tekst: Book a pub that serves fries for 9 people.
Triggery: 1. pub(176.781) | 2. serves(164.109) | 3. people(112.254)
[Top 2] Mahalanobis: 22.1113 | Tekst: Book a churrascaria restaurant that serves chips for five people.
Triggery: 1. book(135.500) | 2. restaurant(130.857) | 3. .(105.091)
[Top 3] Mahalanobis: 21.8741 | Tekst: Book a bar that serves ribs for 5 people.
Triggery: 1. serves(146.441) | 2. that(134.341) | 3. a(128.078)
[Top 4] Mahalanobis: 21.8351 | Tekst: book a gastropub that serves turkish food for 4 people
Triggery: 1. serves(240.590) | 2. b(103.367) | 3. food(72.480)
[Top 5] Mahalanobis: 19.4999 | Tekst: book me a restaurant that serves green bean casserole for five people
Triggery: 1. serves(229.943) | 2. restaurant(161.403) | 3. for(111.887)

===== FOLD 3 =====

Map:   0%|          | 0/9907 [00:00<?, ? examples/s]

Map:   0%|          | 0/4577 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.8747
--- Generowanie XAI dla Foldu 3 ---
[Top 1] Mahalanobis: 9.8941 | Tekst: I'd like to watch Wish You Were Dead
Triggery: 1. watch(97.641) | 2. you(13.247) | 3. like(5.455)
[Top 2] Mahalanobis: 8.9057 | Tekst: Is there a snowstorm in the forecast for El Cenizo
Triggery: 1. storm(20.595) | 2. zo(14.722) | 3. forecast(13.340)
[Top 3] Mahalanobis: 8.6778 | Tekst: I want to watch Wide-Eyed and Ignorant
Triggery: 1. eyed(25.734) | 2. ignorant(8.943) | 3. None(0.000)
[Top 4] Mahalanobis: 8.3960 | Tekst: is Saint Robert hotter than Turkmenistan
Triggery: 1. saint(28.653) | 2. is(15.837) | 3. turkmenistan(7.354)
[Top 5] Mahalanobis: 8.2144 | Tekst: I want to go see The Trouble with Girls
Triggery: 1. girls(13.333) | 2. None(0.000) | 3. None(0.000)

===== FOLD 4 =====

Map:   0%|          | 0/9907 [00:00<?, ? examples/s]

Map:   0%|          | 0/4577 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.8187
--- Generowanie XAI dla Foldu 4 ---
[Top 1] Mahalanobis: 9.5047 | Tekst: play 1988 chant music on Itunes
Triggery: 1. play(55.330) | 2. 1988(15.754) | 3. on(8.860)
[Top 2] Mahalanobis: 9.1282 | Tekst: play Hardcore music
Triggery: 1. music(49.223) | 2. play(41.489) | 3. None(0.000)
[Top 3] Mahalanobis: 9.0425 | Tekst: Play Progressive Metal .
Triggery: 1. .(58.619) | 2. play(25.019) | 3. progressive(11.653)
[Top 4] Mahalanobis: 9.0134 | Tekst: Play music using Last Fm
Triggery: 1. music(2.689) | 2. None(0.000) | 3. None(0.000)
[Top 5] Mahalanobis: 8.7312 | Tekst: Play Clásicos del Hip Hop Español
Triggery: 1. play(68.136) | 2. hop(58.318) | 3. ol(9.193)

===== FOLD 5 =====

Map:   0%|          | 0/9942 [00:00<?, ? examples/s]

Map:   0%|          | 0/4542 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.9246
--- Generowanie XAI dla Foldu 5 ---
[Top 1] Mahalanobis: 13.9787 | Tekst: show me a textbook with a rating of 2 and a maximum rating of 6 that is current
Triggery: 1. textbook(53.277) | 2. current(32.257) | 3. 6(22.024)
[Top 2] Mahalanobis: 12.7520 | Tekst: Hocus Bogus gets a 2 of 6 .
Triggery: 1. gets(49.549) | 2. hoc(18.712) | 3. a(17.578)
[Top 3] Mahalanobis: 12.4576 | Tekst: Rate The Saint in Trouble 1 of 6
Triggery: 1. 6(81.803) | 2. the(73.813) | 3. 1(70.710)
[Top 4] Mahalanobis: 12.4433 | Tekst: rate What the Dog Saw a two
Triggery: 1. a(211.661) | 2. two(147.518) | 3. saw(19.234)
[Top 5] Mahalanobis: 12.4207 | Tekst: I think that The Wizard is a four of 6 .
Triggery: 1. .(77.243) | 2. is(71.182) | 3. 6(67.273)

===== FOLD 6 =====

Map:   0%|          | 0/9944 [00:00<?, ? examples/s]

Map:   0%|          | 0/4540 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.8531
--- Generowanie XAI dla Foldu 6 ---
[Top 1] Mahalanobis: 34.7309 | Tekst: Wish to read the novel called The Wizard of Stone Mountain
Triggery: 1. read(601.674) | 2. novel(263.915) | 3. stone(232.647)
[Top 2] Mahalanobis: 31.5709 | Tekst: find Back for Good , a novel I want to read
Triggery: 1. good(326.518) | 2. read(313.998) | 3. novel(246.955)
[Top 3] Mahalanobis: 31.4314 | Tekst: I want to read the book Between a Rock and a Hard Place
Triggery: 1. read(551.489) | 2. book(412.377) | 3. place(221.497)
[Top 4] Mahalanobis: 29.9846 | Tekst: I want to read the book Crash Landing
Triggery: 1. book(379.312) | 2. read(370.045) | 3. the(193.407)
[Top 5] Mahalanobis: 28.1959 | Tekst: I need a novel about Polymer Chemistry .
Triggery: 1. novel(384.690) | 2. about(235.482) | 3. chemistry(127.696)

===== FOLD 7 =====

Map:   0%|          | 0/9940 [00:00<?, ? examples/s]

Map:   0%|          | 0/4544 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.8294
--- Generowanie XAI dla Foldu 7 ---
[Top 1] Mahalanobis: 20.9634 | Tekst: What is the movie schedule at Cineplex Odeon Corporation 12 hours from now
Triggery: 1. schedule(175.231) | 2. is(139.116) | 3. movie(112.975)
[Top 2] Mahalanobis: 20.6043 | Tekst: what movies are on the movie schedules for five hours from now in the neighbourhood
Triggery: 1. are(199.291) | 2. neighbourhood(171.694) | 3. schedules(111.559)
[Top 3] Mahalanobis: 20.3098 | Tekst: Is the start time 151652 for movies in the neighborhood
Triggery: 1. is(287.825) | 2. movies(187.543) | 3. start(127.443)
[Top 4] Mahalanobis: 20.3073 | Tekst: What movies are starting at eight pm in the area
Triggery: 1. movies(569.615) | 2. are(268.040) | 3. eight(144.991)
[Top 5] Mahalanobis: 20.1404 | Tekst: Is this film going to be at Malco Theatres ?
Triggery: 1. is(291.445) | 2. at(284.385) | 3. be(109.936)

## Główna pętla - R-angle

In [26]:
results_RANGLE = []
xai_lto_rangle = []

for fold_idx, config in enumerate(FOLDS_CONFIG):
    print(f"\n===== FOLD {fold_idx+1}: {config['name']} =====")

    ood_classes = config["ood"]
    id_classes = [c for c in range(7) if c not in ood_classes]

    id_df_full = snips_df[snips_df['label'].isin(id_classes)].copy()
    ood_df_full = snips_df[snips_df['label'].isin(ood_classes)].copy()

    train_id, test_id = train_test_split(
        id_df_full,
        test_size=0.2,
        stratify=id_df_full['label'],
        random_state=42
    )

    train_df_fold = train_id
    test_df_fold = pd.concat([test_id, ood_df_full]).sample(frac=1, random_state=42)

    mapping = {old_id: new_id for new_id, old_id in enumerate(id_classes)}

    train_df_fold['mapped_label'] = train_df_fold['label'].map(mapping)

    train_ds = Dataset.from_pandas(
        train_df_fold[['text', 'mapped_label']].rename(columns={'mapped_label': 'label'})
    ).map(tokenize_fn, batched=True)

    test_ds = Dataset.from_pandas(test_df_fold).map(tokenize_fn, batched=True)

    train_ds = train_ds.remove_columns([col for col in train_ds.column_names if col not in ["input_ids", "attention_mask", "label"]])
    test_ds = test_ds.remove_columns([col for col in test_ds.column_names if col not in ["input_ids", "attention_mask"]])

    train_ds.set_format(type='torch')
    test_ds.set_format(type='torch')

    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=len(id_classes)
    )

    training_args = TrainingArguments(
        output_dir="./tmp",
        num_train_epochs=3,
        per_device_train_batch_size=32,
        eval_strategy="no",
        save_strategy="no",
        logging_steps=100,
        report_to="none",
        fp16=True
    )

    trainer = ContrastiveTrainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        data_collator=data_collator,
        lambda_param=2.0 # Waga z artykułu
    )
    trainer.train()

    train_embeddings = get_embeddings(model, train_ds)
    test_embeddings = get_embeddings(model, test_ds)

    train_labels = train_df_fold['mapped_label'].values
    true_labels = test_df_fold['label'].values

    class_means = []
    for c in range(len(id_classes)):
        class_means.append(train_embeddings[train_labels == c].mean(axis=0))

    class_means = np.array(class_means)

    def r_angle(x, mean):
        cos_sim = cosine_similarity([x], [mean])[0][0]
        cos_sim = np.clip(cos_sim, -1.0, 1.0)
        return np.arccos(cos_sim)

    scores = []

    for x in test_embeddings:
        angles = [r_angle(x, m) for m in class_means]
        scores.append(min(angles))  # najbliższa klasa

    scores = np.array(scores)

    y_true = np.array([1 if l in ood_classes else 0 for l in true_labels])

    auroc = roc_auc_score(y_true, scores)

    precision_arr, recall_arr, _ = precision_recall_curve(y_true, scores)
    aupr = auc(recall_arr, precision_arr)

    fpr, tpr, thresholds = roc_curve(y_true, scores)
    idx_95 = np.argmin(np.abs(tpr - 0.95))
    fpr95 = fpr[idx_95]

    print(f"AUROC: {auroc:.4f}")

    # print(f"Generowanie wykresu t-SNE dla Foldu {fold_idx+1}...")

    # X_fold = test_embeddings

    # y_fold_names = []
    # for label in true_labels:
    #     if label in ood_classes:
    #         y_fold_names.append(f"OOD (Klasa {label})")
    #     else:
    #         y_fold_names.append(f"ID (Klasa {label})")

    # tsne = TSNE(n_components=2, random_state=42, init='pca', learning_rate='auto')
    # projections = tsne.fit_transform(X_fold)

    # fig = px.scatter(
    #     x=projections[:, 0],
    #     y=projections[:, 1],
    #     color=y_fold_names,
    #     title=f"Przestrzeń ukryta BERT - Fold {fold_idx+1}: {config['name']} (Zb. Testowy)",
    #     labels={'color': 'Rodzaj intencji', 'x': 'Wymiar 1', 'y': 'Wymiar 2'},
    #     opacity=0.8
    # )

    # fig.update_traces(marker=dict(size=4))

    # html_path = f"{SAVE_PATH}/rangle_tsne_fold_{fold_idx+1}.html"
    # fig.write_html(html_path)
    # print(f"✅ Zapisano wykres: {html_path}")

    results_RANGLE.append({
        "fold": fold_idx + 1,
        "scenario": config["name"],
        "auroc": auroc,
        "aupr": aupr,
        "fpr95": fpr95
    })

    print(f"--- Generowanie XAI dla Foldu {fold_idx + 1} ---")

    class_means_tensor = torch.tensor(class_means, dtype=torch.float32).to(device)

    lig = LayerIntegratedGradients(r_angle_ood_score, model.get_input_embeddings())

    top_5_indices = np.argsort(scores)[::-1][:5]
    special_tokens = tokenizer.all_special_tokens

    for rank, idx in enumerate(top_5_indices, 1):
        sample_text = test_df_fold.iloc[idx]['text']
        score = scores[idx]

        inputs = tokenizer(sample_text, return_tensors="pt", truncation=True, padding=True)
        input_ids_pt = inputs["input_ids"].to(device)
        attention_mask_pt = inputs["attention_mask"].to(device)

        attributions = lig.attribute(
            inputs=input_ids_pt, target=None, additional_forward_args=(attention_mask_pt,)
        )

        attributions_sum = attributions.sum(dim=-1).squeeze(0).cpu().detach().numpy()
        tokens = tokenizer.convert_ids_to_tokens(input_ids_pt[0])

        word_attributions = [
            (tok.replace('Ġ', '').replace('##', ''), attr)
            for tok, attr in zip(tokens, attributions_sum) if tok not in special_tokens
        ]

        top_tokens = sorted([attr for attr in word_attributions if attr[1] > 0], key=lambda x: x[1], reverse=True)[:3]

        t1, w1 = top_tokens[0] if len(top_tokens) > 0 else (None, 0.0)
        t2, w2 = top_tokens[1] if len(top_tokens) > 1 else (None, 0.0)
        t3, w3 = top_tokens[2] if len(top_tokens) > 2 else (None, 0.0)

        print(f"[Top {rank}] R-angle: {score:.4f} | Tekst: {sample_text}")
        print(f"Triggery: 1. {t1}({w1:.3f}) | 2. {t2}({w2:.3f}) | 3. {t3}({w3:.3f})")

        xai_lto_rangle.append({
            "fold": fold_idx + 1,
            "scenario": config["name"],
            "rank_in_fold": rank,
            "text": sample_text,
            "score": score,
            "trigger_1_token": t1,
            "trigger_1_weight": float(w1) if t1 else 0.0,
            "trigger_2_token": t2,
            "trigger_2_weight": float(w2) if t2 else 0.0,
            "trigger_3_token": t3,
            "trigger_3_weight": float(w3) if t3 else 0.0
        })
xai_df = pd.DataFrame(xai_lto_rangle)
xai_df.to_csv("xai/contrastive_xai_lto_rangle.csv", index=False)

===== FOLD 1: Kino =====

Map:   0%|          | 0/8296 [00:00<?, ? examples/s]

Map:   0%|          | 0/6188 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.9794
--- Generowanie XAI dla Foldu 1 ---
[Top 1] R-angle: 1.1194 | Tekst: Can i get the showtimes for Man in Blues ?
Triggery: 1. in(0.359) | 2. for(0.298) | 3. the(0.295)
[Top 2] R-angle: 1.0983 | Tekst: show the creativity of Where What When
Triggery: 1. creativity(0.700) | 2. what(0.046) | 3. of(0.005)
[Top 3] R-angle: 1.0876 | Tekst: looking for Liberalism and the Limits of Justice
Triggery: 1. liberalism(0.305) | 2. justice(0.236) | 3. looking(0.172)
[Top 4] R-angle: 1.0870 | Tekst: find a photograph called Wild Cats on the Beach
Triggery: 1. photograph(0.426) | 2. on(0.338) | 3. beach(0.304)
[Top 5] R-angle: 1.0806 | Tekst: Find time for Ace of the Saddle
Triggery: 1. ace(0.262) | 2. of(0.228) | 3. saddle(0.169)

===== FOLD 2: Muzyka =====

Map:   0%|          | 0/8273 [00:00<?, ? examples/s]

Map:   0%|          | 0/6211 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.7863
--- Generowanie XAI dla Foldu 2 ---
[Top 1] R-angle: 0.8659 | Tekst: add chas chandler to my Aux Cord Privileges
Triggery: 1. privileges(0.338) | 2. my(0.071) | 3. to(0.064)
[Top 2] R-angle: 0.8657 | Tekst: I want to add un jour dans notre vie to my list running to rock 170 to 190 bpm
Triggery: 1. running(0.347) | 2. list(0.176) | 3. to(0.169)
[Top 3] R-angle: 0.8625 | Tekst: this track should get added to Spain Top 50
Triggery: 1. top(0.233) | 2. 50(0.134) | 3. spain(0.060)
[Top 4] R-angle: 0.8557 | Tekst: add Stephen McNally to Confidence Boost
Triggery: 1. nally(0.131) | 2. boost(0.084) | 3. stephen(0.083)
[Top 5] R-angle: 0.8218 | Tekst: I want global top 50 to have marit bergman added to it.
Triggery: 1. bergman(0.064) | 2. top(0.055) | 3. global(0.053)

===== FOLD 3: Usługi =====

Map:   0%|          | 0/8248 [00:00<?, ? examples/s]

Map:   0%|          | 0/6236 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.8243
--- Generowanie XAI dla Foldu 3 ---
[Top 1] R-angle: 1.0158 | Tekst: I need to book a pub for 8 that has wifi
Triggery: 1. 8(0.211) | 2. i(0.192) | 3. book(0.084)
[Top 2] R-angle: 0.9949 | Tekst: book a highly rated restaurant in Central African Republic for 5 people on sep. the second
Triggery: 1. rated(1.158) | 2. 5(0.528) | 3. on(0.351)
[Top 3] R-angle: 0.9840 | Tekst: I would like to book the best food court with persian food within the same area as OK for my ex husband and I
Triggery: 1. area(0.428) | 2. within(0.305) | 3. with(0.223)
[Top 4] R-angle: 0.9823 | Tekst: I would like reservations made for Masonville , Vermont nov. 7
Triggery: 1. nov(0.134) | 2. reservations(0.056) | 3. mason(0.043)
[Top 5] R-angle: 0.9319 | Tekst: Book me a bar that's highly rated for georgia and I in Burkina
Triggery: 1. rated(0.428) | 2. book(0.106) | 3. for(0.045)

===== FOLD 4: Twórczość =====

Map:   0%|          | 0/8299 [00:00<?, ? examples/s]

Map:   0%|          | 0/6185 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.9612
--- Generowanie XAI dla Foldu 4 ---
[Top 1] R-angle: 1.1642 | Tekst: Rate Maps for Lost Lovers 1 of 6
Triggery: 1. lovers(0.223) | 2. 1(0.158) | 3. rate(0.081)
[Top 2] R-angle: 1.1526 | Tekst: Rate Voyages by Starlight a value of 0
Triggery: 1. voyages(0.356) | 2. of(0.216) | 3. by(0.075)
[Top 3] R-angle: 1.1308 | Tekst: Big Breasts and Wide Hips is terrible and 1 out of 6
Triggery: 1. breasts(0.356) | 2. hips(0.187) | 3. wide(0.075)
[Top 4] R-angle: 1.1119 | Tekst: Can I rate the book My Life in France not one , but 6 stars ?
Triggery: 1. book(0.442) | 2. rate(0.226) | 3. the(0.167)
[Top 5] R-angle: 1.0964 | Tekst: rate How to Eat Fried Worms two stars
Triggery: 1. eat(0.314) | 2. rate(0.275) | 3. worms(0.184)

===== FOLD 5: Mieszany =====

Map:   0%|          | 0/8281 [00:00<?, ? examples/s]

Map:   0%|          | 0/6203 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.8815
--- Generowanie XAI dla Foldu 5 ---
[Top 1] R-angle: 1.2546 | Tekst: I need a table at The Apple Pan for reva and bernadine
Triggery: 1. table(0.267) | 2. apple(0.150) | 3. a(0.131)
[Top 2] R-angle: 1.1859 | Tekst: Book a restaurant that serves capicollo in Kit Carson with ilene and aisha .
Triggery: 1. serves(0.224) | 2. a(0.172) | 3. with(0.152)
[Top 3] R-angle: 1.1563 | Tekst: Set me up with a table at a bar with salade for 5
Triggery: 1. set(0.188) | 2. 5(0.082) | 3. me(0.072)
[Top 4] R-angle: 1.1526 | Tekst: I need a table for 5 at a brasserie that has a reuben sandwich
Triggery: 1. reuben(0.314) | 2. table(0.272) | 3. at(0.174)
[Top 5] R-angle: 1.1304 | Tekst: Book a reservation for a gastropub serving liver and onions
Triggery: 1. book(0.314) | 2. reservation(0.205) | 3. for(0.063)

## Leave One Out - R-angle

In [27]:
results_LOO_RANGLE = []
xai_loo_rangle = []

for fold_idx in range(7):
    print(f"\n===== FOLD {fold_idx+1} =====")

    ood_classes = [fold_idx]
    id_classes = [c for c in range(7) if c not in ood_classes]

    id_df_full = snips_df[snips_df['label'].isin(id_classes)].copy()
    ood_df_full = snips_df[snips_df['label'].isin(ood_classes)].copy()

    train_id, test_id = train_test_split(
        id_df_full,
        test_size=0.2,
        stratify=id_df_full['label'],
        random_state=42
    )

    train_df_fold = train_id
    test_df_fold = pd.concat([test_id, ood_df_full]).sample(frac=1, random_state=42)

    mapping = {old_id: new_id for new_id, old_id in enumerate(id_classes)}

    train_df_fold['mapped_label'] = train_df_fold['label'].map(mapping)

    train_ds = Dataset.from_pandas(
        train_df_fold[['text', 'mapped_label']].rename(columns={'mapped_label': 'label'})
    ).map(tokenize_fn, batched=True)

    test_ds = Dataset.from_pandas(test_df_fold).map(tokenize_fn, batched=True)

    train_ds = train_ds.remove_columns([col for col in train_ds.column_names if col not in ["input_ids", "attention_mask", "label"]])
    test_ds = test_ds.remove_columns([col for col in test_ds.column_names if col not in ["input_ids", "attention_mask"]])

    train_ds.set_format(type='torch')
    test_ds.set_format(type='torch')

    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=len(id_classes)
    )

    training_args = TrainingArguments(
        output_dir="./tmp",
        num_train_epochs=3,
        per_device_train_batch_size=32,
        eval_strategy="no",
        save_strategy="no",
        logging_steps=100,
        report_to="none",
        fp16=True
    )

    trainer = ContrastiveTrainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        data_collator=data_collator,
        lambda_param=2.0 # Waga z artykułu
    )
    trainer.train()

    train_embeddings = get_embeddings(model, train_ds)
    test_embeddings = get_embeddings(model, test_ds)

    train_labels = train_df_fold['mapped_label'].values
    true_labels = test_df_fold['label'].values

    class_means = []
    for c in range(len(id_classes)):
        class_means.append(train_embeddings[train_labels == c].mean(axis=0))

    class_means = np.array(class_means)

    def r_angle(x, mean):
        cos_sim = cosine_similarity([x], [mean])[0][0]
        cos_sim = np.clip(cos_sim, -1.0, 1.0)
        return np.arccos(cos_sim)

    scores = []

    for x in test_embeddings:
        angles = [r_angle(x, m) for m in class_means]
        scores.append(min(angles))  # najbliższa klasa

    scores = np.array(scores)

    y_true = np.array([1 if l in ood_classes else 0 for l in true_labels])

    auroc = roc_auc_score(y_true, scores)

    precision_arr, recall_arr, _ = precision_recall_curve(y_true, scores)
    aupr = auc(recall_arr, precision_arr)

    fpr, tpr, thresholds = roc_curve(y_true, scores)
    idx_95 = np.argmin(np.abs(tpr - 0.95))
    fpr95 = fpr[idx_95]

    print(f"AUROC: {auroc:.4f}")

    # print(f"Generowanie wykresu t-SNE dla Foldu {fold_idx+1}...")

    # X_fold = test_embeddings

    # y_fold_names = []
    # for label in true_labels:
    #     if label in ood_classes:
    #         y_fold_names.append(f"OOD (Klasa {label})")
    #     else:
    #         y_fold_names.append(f"ID (Klasa {label})")

    # tsne = TSNE(n_components=2, random_state=42, init='pca', learning_rate='auto')
    # projections = tsne.fit_transform(X_fold)

    # fig = px.scatter(
    #     x=projections[:, 0],
    #     y=projections[:, 1],
    #     color=y_fold_names,
    #     title=f"Przestrzeń ukryta BERT - Fold {fold_idx+1} (Zb. Testowy)",
    #     labels={'color': 'Rodzaj intencji', 'x': 'Wymiar 1', 'y': 'Wymiar 2'},
    #     opacity=0.8
    # )

    # fig.update_traces(marker=dict(size=4))

    # html_path = f"{SAVE_PATH}/rangle_loo_tsne_fold_{fold_idx+1}.html"
    # fig.write_html(html_path)
    # print(f"✅ Zapisano wykres: {html_path}")

    results_LOO_RANGLE.append({
        "fold": fold_idx + 1,
        "scenario": f"OOD_Class_{fold_idx+1}",
        "auroc": auroc,
        "aupr": aupr,
        "fpr95": fpr95
    })

    print(f"--- Generowanie XAI dla Foldu {fold_idx + 1} ---")

    class_means_tensor = torch.tensor(class_means, dtype=torch.float32).to(device)

    lig = LayerIntegratedGradients(r_angle_ood_score, model.get_input_embeddings())

    top_5_indices = np.argsort(scores)[::-1][:5]
    special_tokens = tokenizer.all_special_tokens

    for rank, idx in enumerate(top_5_indices, 1):
        sample_text = test_df_fold.iloc[idx]['text']
        score = scores[idx]

        inputs = tokenizer(sample_text, return_tensors="pt", truncation=True, padding=True)
        input_ids_pt = inputs["input_ids"].to(device)
        attention_mask_pt = inputs["attention_mask"].to(device)

        attributions = lig.attribute(
            inputs=input_ids_pt, target=None, additional_forward_args=(attention_mask_pt,)
        )

        attributions_sum = attributions.sum(dim=-1).squeeze(0).cpu().detach().numpy()
        tokens = tokenizer.convert_ids_to_tokens(input_ids_pt[0])

        word_attributions = [
            (tok.replace('Ġ', '').replace('##', ''), attr)
            for tok, attr in zip(tokens, attributions_sum) if tok not in special_tokens
        ]

        top_tokens = sorted([attr for attr in word_attributions if attr[1] > 0], key=lambda x: x[1], reverse=True)[:3]

        t1, w1 = top_tokens[0] if len(top_tokens) > 0 else (None, 0.0)
        t2, w2 = top_tokens[1] if len(top_tokens) > 1 else (None, 0.0)
        t3, w3 = top_tokens[2] if len(top_tokens) > 2 else (None, 0.0)

        print(f"[Top {rank}] R-angle: {score:.4f} | Tekst: {sample_text}")
        print(f"Triggery: 1. {t1}({w1:.3f}) | 2. {t2}({w2:.3f}) | 3. {t3}({w3:.3f})")

        xai_loo_rangle.append({
            "fold": fold_idx + 1,
            "scenario": f"OOD_Class_{fold_idx+1}",
            "rank_in_fold": rank,
            "text": sample_text,
            "score": score,
            "trigger_1_token": t1,
            "trigger_1_weight": float(w1) if t1 else 0.0,
            "trigger_2_token": t2,
            "trigger_2_weight": float(w2) if t2 else 0.0,
            "trigger_3_token": t3,
            "trigger_3_weight": float(w3) if t3 else 0.0
        })
xai_df = pd.DataFrame(xai_loo_rangle)
xai_df.to_csv("xai/contrastive_xai_loo_rangle.csv", index=False)

===== FOLD 1 =====

Map:   0%|          | 0/9953 [00:00<?, ? examples/s]

Map:   0%|          | 0/4531 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.7837
--- Generowanie XAI dla Foldu 1 ---
[Top 1] R-angle: 1.1664 | Tekst: Add impossible is nothing to SPA Treatment
Triggery: 1. treatment(0.215) | 2. to(0.142) | 3. spa(0.079)
[Top 2] R-angle: 0.9131 | Tekst: add darkest angels to my SOS 48 2016
Triggery: 1. so(0.245) | 2. 2016(0.093) | 3. angels(0.047)
[Top 3] R-angle: 0.8972 | Tekst: add naomi schemer to my Hanging Out and Relaxing
Triggery: 1. naomi(0.202) | 2. r(0.086) | 3. relaxing(0.084)
[Top 4] R-angle: 0.8763 | Tekst: Add Perfect Sense, Part I to my women of classical list
Triggery: 1. list(0.191) | 2. part(0.101) | 3. of(0.095)
[Top 5] R-angle: 0.8554 | Tekst: Add a track to my list Made in Puerto Rico
Triggery: 1. list(0.306) | 2. my(0.062) | 3. add(0.035)

===== FOLD 2 =====

Map:   0%|          | 0/9928 [00:00<?, ? examples/s]

Map:   0%|          | 0/4556 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.9713
--- Generowanie XAI dla Foldu 2 ---
[Top 1] R-angle: 1.2177 | Tekst: Please book a joint type restaurant room with spa facility to accommodate 8 members
Triggery: 1. restaurant(0.307) | 2. members(0.292) | 3. to(0.240)
[Top 2] R-angle: 1.1873 | Tekst: Book a table at a bar in Moody for deloris, ester and petra alvarez .
Triggery: 1. bar(0.349) | 2. alvarez(0.239) | 3. a(0.182)
[Top 3] R-angle: 1.1494 | Tekst: Book a reservation for 4 people at a restaurant within the same area as my step daughter's position
Triggery: 1. at(0.232) | 2. book(0.203) | 3. as(0.186)
[Top 4] R-angle: 1.1459 | Tekst: book a table in Hallwood for one for supper
Triggery: 1. in(0.355) | 2. wood(0.242) | 3. table(0.239)
[Top 5] R-angle: 1.1366 | Tekst: Book a bar that serves ribs for 5 people.
Triggery: 1. serves(0.379) | 2. ribs(0.215) | 3. a(0.169)

===== FOLD 3 =====

Map:   0%|          | 0/9907 [00:00<?, ? examples/s]

Map:   0%|          | 0/4577 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.9715
--- Generowanie XAI dla Foldu 3 ---
[Top 1] R-angle: 1.0332 | Tekst: Is it chillier in Mint Hill FM
Triggery: 1. chill(0.129) | 2. is(0.126) | 3. hill(0.108)
[Top 2] R-angle: 1.0100 | Tekst: Is it going to get hotter in my current position
Triggery: 1. get(0.049) | 2. None(0.000) | 3. None(0.000)
[Top 3] R-angle: 0.9336 | Tekst: is hail in the weather forecast for Monterey Bay National Marine Sanctuary
Triggery: 1. forecast(0.159) | 2. monterey(0.032) | 3. the(0.018)
[Top 4] R-angle: 0.8913 | Tekst: What's the wather in Coleville , Kenya
Triggery: 1. what(0.517) | 2. her(0.071) | 3. wat(0.029)
[Top 5] R-angle: 0.8894 | Tekst: I need the weather in ND in three hundred fifty one days
Triggery: 1. weather(0.524) | 2. days(0.076) | 3. d(0.034)

===== FOLD 4 =====

Map:   0%|          | 0/9907 [00:00<?, ? examples/s]

Map:   0%|          | 0/4577 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.9485
--- Generowanie XAI dla Foldu 4 ---
[Top 1] R-angle: 0.9635 | Tekst: Please start playing some thirties theme music.
Triggery: 1. theme(0.165) | 2. music(0.161) | 3. start(0.097)
[Top 2] R-angle: 0.9193 | Tekst: I want to hear Choice on Last Fm from the twenties .
Triggery: 1. on(0.255) | 2. .(0.095) | 3. to(0.061)
[Top 3] R-angle: 0.8737 | Tekst: give me some Hank Shermann from 1975 on Lastfm
Triggery: 1. me(0.246) | 2. last(0.078) | 3. sherman(0.025)
[Top 4] R-angle: 0.8703 | Tekst: I need some ambient music.
Triggery: 1. need(0.222) | 2. i(0.057) | 3. some(0.025)
[Top 5] R-angle: 0.8700 | Tekst: Play a 2011 ballad by Evil Jared Hasselhoff on Lastfm .
Triggery: 1. play(0.273) | 2. on(0.229) | 3. fm(0.053)

===== FOLD 5 =====

Map:   0%|          | 0/9942 [00:00<?, ? examples/s]

Map:   0%|          | 0/4542 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.9866
--- Generowanie XAI dla Foldu 5 ---
[Top 1] R-angle: 1.2473 | Tekst: I think this textbook should have a rating of four and a best rating of 6
Triggery: 1. textbook(0.226) | 2. 6(0.145) | 3. rating(0.119)
[Top 2] R-angle: 1.2078 | Tekst: the current rating of 6 out of two for a textbook
Triggery: 1. textbook(0.307) | 2. rating(0.235) | 3. of(0.084)
[Top 3] R-angle: 1.2040 | Tekst: I would rate this book a value of 3 and a best rating of 6
Triggery: 1. rate(0.128) | 2. rating(0.082) | 3. i(0.073)
[Top 4] R-angle: 1.1990 | Tekst: rating points for Castles of Steel out of 6 are 5
Triggery: 1. points(0.381) | 2. castles(0.359) | 3. steel(0.248)
[Top 5] R-angle: 1.1873 | Tekst: I would give this textbook a rating of 0 and a best rating of 6
Triggery: 1. textbook(0.151) | 2. 0(0.103) | 3. would(0.097)

===== FOLD 6 =====

Map:   0%|          | 0/9944 [00:00<?, ? examples/s]

Map:   0%|          | 0/4540 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.9679
--- Generowanie XAI dla Foldu 6 ---
[Top 1] R-angle: 1.0960 | Tekst: Find book The Music Lovers
Triggery: 1. find(0.246) | 2. book(0.161) | 3. lovers(0.091)
[Top 2] R-angle: 1.0315 | Tekst: look for the creative work The Testament of Gideon Mack
Triggery: 1. creative(0.192) | 2. for(0.117) | 3. gideon(0.088)
[Top 3] R-angle: 1.0290 | Tekst: Look for the creative work called White Sugar
Triggery: 1. look(0.214) | 2. the(0.116) | 3. work(0.060)
[Top 4] R-angle: 0.9998 | Tekst: I need Top Gear 2 , please search it for me.
Triggery: 1. search(0.105) | 2. .(0.081) | 3. i(0.029)
[Top 5] R-angle: 0.9783 | Tekst: show 50 Words for Snow creative picture
Triggery: 1. 50(0.334) | 2. show(0.308) | 3. for(0.275)

===== FOLD 7 =====

Map:   0%|          | 0/9940 [00:00<?, ? examples/s]

Map:   0%|          | 0/4544 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AUROC: 0.9187
--- Generowanie XAI dla Foldu 7 ---
[Top 1] R-angle: 1.1406 | Tekst: Is The Belles of St. Clements playing at Star Theatres in 8 minutes ?
Triggery: 1. playing(0.696) | 2. minutes(0.228) | 3. star(0.154)
[Top 2] R-angle: 1.0579 | Tekst: Is Warhead playing at AMC Theaters
Triggery: 1. is(0.680) | 2. theaters(0.246) | 3. war(0.072)
[Top 3] R-angle: 1.0169 | Tekst: What time is Careful, He Might Hear You playing at the cinema
Triggery: 1. at(0.528) | 2. time(0.332) | 3. what(0.293)
[Top 4] R-angle: 0.9851 | Tekst: Is A Tree Grows in Brooklyn playing in one hour
Triggery: 1. playing(0.183) | 2. is(0.098) | 3. brooklyn(0.080)
[Top 5] R-angle: 0.9835 | Tekst: Can I get the movie schedules for Loews Cineplex in six hours seventeen minutes and eighteen seconds .
Triggery: 1. schedules(0.110) | 2. the(0.072) | 3. ne(0.068)

## RESULTS

In [ ]:
df_MAHALANOBIS = pd.DataFrame(results_MAHALANOBIS)

print("\n==== FINAL MAHALANOBIS ====")
print(df_MAHALANOBIS)

summary = {
    "Metric": ["AUROC", "AUPR", "FPR95"],
    "Mean": [
        df_MAHALANOBIS["auroc"].mean(),
        df_MAHALANOBIS["aupr"].mean(),
        df_MAHALANOBIS["fpr95"].mean()
    ],
    "Std": [
        df_MAHALANOBIS["auroc"].std(),
        df_MAHALANOBIS["aupr"].std(),
        df_MAHALANOBIS["fpr95"].std()
    ]
}

df_summary = pd.DataFrame(summary)
print(df_summary)

==== FINAL MAHALANOBIS ====
   fold   scenario     auroc      aupr     fpr95
0     1       Kino  0.920976  0.963432  0.492048
1     2     Muzyka  0.719803  0.825328  0.846303
2     3     Usługi  0.806145  0.891851  0.792535
3     4  Twórczość  0.843232  0.923711  0.711807
4     5   Mieszany  0.850747  0.920303  0.715113
  Metric      Mean       Std
0  AUROC  0.828181  0.073447
1   AUPR  0.904925  0.051281
2  FPR95  0.711561  0.135010

In [ ]:
detailed_path = f"{SAVE_PATH}/wyniki_mahalanobis.csv"
df_MAHALANOBIS.to_csv(detailed_path, index=False)
print(f"Zapisano wyniki szczegółowe: {detailed_path}")

df_summary = pd.DataFrame(summary)

summary_path = f"{SAVE_PATH}/podsumowanie_mahalanobis.csv"
df_summary.to_csv(summary_path, index=False)

print(f"Zapisano podsumowanie statystyczne: {summary_path}")

Zapisano wyniki szczegółowe: /content/drive/MyDrive/SNIPS_OOD_Project/wyniki_mahalanobis.csv
Zapisano podsumowanie statystyczne: /content/drive/MyDrive/SNIPS_OOD_Project/podsumowanie_mahalanobis.csv

In [ ]:
df_LOO_MAHALANOBIS = pd.DataFrame(results_LOO_MAHALANOBIS)

print("\n==== FINAL LOO MAHALANOBIS ====")
print(df_LOO_MAHALANOBIS)

loo_summary = {
    "Metric": ["AUROC", "AUPR", "FPR95"],
    "Mean": [
        df_LOO_MAHALANOBIS["auroc"].mean(),
        df_LOO_MAHALANOBIS["aupr"].mean(),
        df_LOO_MAHALANOBIS["fpr95"].mean()
    ],
    "Std": [
        df_LOO_MAHALANOBIS["auroc"].std(),
        df_LOO_MAHALANOBIS["aupr"].std(),
        df_LOO_MAHALANOBIS["fpr95"].std()
    ]
}

df_loo_summary = pd.DataFrame(loo_summary)
print(df_loo_summary)

==== FINAL LOO MAHALANOBIS ====
   fold     scenario     auroc      aupr     fpr95
0     1  OOD_Class_1  0.641618  0.583359  0.816794
1     2  OOD_Class_2  0.908192  0.907824  0.499396
2     3  OOD_Class_3  0.870053  0.808266  0.448930
3     4  OOD_Class_4  0.770628  0.720560  0.732338
4     5  OOD_Class_5  0.920007  0.911721  0.407884
5     6  OOD_Class_6  0.813081  0.825975  0.747788
6     7  OOD_Class_7  0.801463  0.795770  0.741247
  Metric      Mean       Std
0  AUROC  0.817863  0.095657
1   AUPR  0.793354  0.113874
2  FPR95  0.627768  0.168700

In [ ]:
detailed_path = f"{SAVE_PATH}/wyniki_loo_mahalanobis.csv"
df_LOO_MAHALANOBIS.to_csv(detailed_path, index=False)
print(f"Zapisano wyniki szczegółowe: {detailed_path}")

df_loo_summary = pd.DataFrame(loo_summary)

summary_path = f"{SAVE_PATH}/podsumowanie_loo_mahalanobis.csv"
df_loo_summary.to_csv(summary_path, index=False)

print(f"Zapisano podsumowanie statystyczne: {summary_path}")

Zapisano wyniki szczegółowe: /content/drive/MyDrive/SNIPS_OOD_Project/wyniki_loo_mahalanobis.csv
Zapisano podsumowanie statystyczne: /content/drive/MyDrive/SNIPS_OOD_Project/podsumowanie_loo_mahalanobis.csv

In [ ]:
df_RANGLE = pd.DataFrame(results_RANGLE)

print("\n==== FINAL R-ANGLE ====")
print(df_RANGLE)

summary_rangle = {
    "Metric": ["AUROC", "AUPR", "FPR95"],
    "Mean": [
        df_RANGLE["auroc"].mean(),
        df_RANGLE["aupr"].mean(),
        df_RANGLE["fpr95"].mean()
    ],
    "Std": [
        df_RANGLE["auroc"].std(),
        df_RANGLE["aupr"].std(),
        df_RANGLE["fpr95"].std()
    ]
}

df_summary_rangle = pd.DataFrame(summary_rangle)
print(df_summary_rangle)

==== FINAL R-ANGLE ====
   fold   scenario     auroc      aupr     fpr95
0     1       Kino  0.977389  0.989535  0.114217
1     2     Muzyka  0.778140  0.835797  0.643306
2     3     Usługi  0.844033  0.903027  0.590402
3     4  Twórczość  0.959304  0.978329  0.202892
4     5   Mieszany  0.903772  0.949367  0.511347
  Metric      Mean       Std
0  AUROC  0.892527  0.082497
1   AUPR  0.931211  0.062948
2  FPR95  0.412433  0.238537

In [ ]:
detailed_path = f"{SAVE_PATH}/wyniki_rangle.csv"
df_RANGLE.to_csv(detailed_path, index=False)
print(f"Zapisano wyniki szczegółowe: {detailed_path}")

summary_path = f"{SAVE_PATH}/podsumowanie_rangle.csv"
df_summary_rangle.to_csv(summary_path, index=False)

print(f"Zapisano podsumowanie statystyczne: {summary_path}")

Zapisano wyniki szczegółowe: /content/drive/MyDrive/SNIPS_OOD_Project/wyniki_rangle.csv
Zapisano podsumowanie statystyczne: /content/drive/MyDrive/SNIPS_OOD_Project/podsumowanie_rangle.csv

In [ ]:
df_LOO_RANGLE = pd.DataFrame(results_LOO_RANGLE)

print("\n==== FINAL LOO R-ANGLE ====")
print(df_LOO_RANGLE)

summary_loo_rangle = {
    "Metric": ["AUROC", "AUPR", "FPR95"],
    "Mean": [
        df_LOO_RANGLE["auroc"].mean(),
        df_LOO_RANGLE["aupr"].mean(),
        df_LOO_RANGLE["fpr95"].mean()
    ],
    "Std": [
        df_LOO_RANGLE["auroc"].std(),
        df_LOO_RANGLE["aupr"].std(),
        df_LOO_RANGLE["fpr95"].std()
    ]
}

df_summary_loo_rangle = pd.DataFrame(summary_loo_rangle)
print(df_summary_loo_rangle)

==== FINAL LOO R-ANGLE ====
   fold     scenario     auroc      aupr     fpr95
0     1  OOD_Class_1  0.794662  0.725550  0.577742
1     2  OOD_Class_2  0.975106  0.964112  0.071687
2     3  OOD_Class_3  0.975590  0.953675  0.052887
3     4  OOD_Class_4  0.936708  0.906077  0.244651
4     5  OOD_Class_5  0.982263  0.973334  0.053902
5     6  OOD_Class_6  0.969843  0.965340  0.146018
6     7  OOD_Class_7  0.916257  0.905812  0.424950
  Metric      Mean       Std
0  AUROC  0.935776  0.066769
1   AUPR  0.913414  0.087447
2  FPR95  0.224548  0.205521

In [ ]:
detailed_path = f"{SAVE_PATH}/wyniki_loo_rangle.csv"
df_LOO_RANGLE.to_csv(detailed_path, index=False)
print(f"Zapisano wyniki szczegółowe: {detailed_path}")

summary_path = f"{SAVE_PATH}/podsumowanie_loo_rangle.csv"
df_summary_loo_rangle.to_csv(summary_path, index=False)

print(f"Zapisano podsumowanie statystyczne: {summary_path}")

Zapisano wyniki szczegółowe: /content/drive/MyDrive/SNIPS_OOD_Project/wyniki_loo_rangle.csv
Zapisano podsumowanie statystyczne: /content/drive/MyDrive/SNIPS_OOD_Project/podsumowanie_loo_rangle.csv