In [7]:
!pip install -q transformers datasets evaluate groq accelerate scikit-learn transformers_interpret

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.9/45.9 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.8/45.8 kB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 455.2/455.2 kB 18.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 48.7 MB/s eta 0:00:00

In [2]:
import os
import torch
import numpy as np
import pandas as pd
from groq import Groq
from datasets import load_dataset, Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score, precision_recall_curve, auc, roc_curve
from google.colab import drive
from sklearn.model_selection import train_test_split

In [3]:
# ==========================================
# KONFIGURACJA I MONTOWANIE DYSKU
# ==========================================
drive.mount('/content/drive')
SAVE_PATH = "/content/drive/MyDrive/SNIPS_OOD_Project"
if not os.path.exists(SAVE_PATH):
    os.makedirs(SAVE_PATH)

GROQ_API_KEY = "secret_key"  # <--- WPISZ TUTAJ SWÓJ KLUCZ
MODEL_NAME = "bert-base-uncased"
NUM_FOLDS = 5
NUM_OOD_SAMPLES = 1750

Mounted at /content/drive

In [4]:
def generate_unknown_data(n):
    print(f"--- Generowanie {n} przykładów klasy Unknown przez Groq ---")
    client = Groq(api_key=GROQ_API_KEY)

    prompt = f"""
Generate {n} short voice assistant commands (3–10 words each).

These must be OUT-OF-DISTRIBUTION (OOD) relative to SNIPS dataset.

SNIPS contains intents about:
- weather
- music playback
- restaurant booking
- taxi booking
- flight booking
- alarm setting
- general search / navigation

STRICT RULES:
- DO NOT generate anything related to: weather, music, alarms, reminders, restaurants, taxis, flights
- DO NOT paraphrase these intents
- DO NOT produce assistant-style commands like "set alarm", "play song", "book table"

Allowed OOD domains:
- legal or government info requests
- abstract questions (philosophy, definitions)
- technical instructions (coding, engineering concepts)
- medical information queries (non-appointment)
- financial explanations (not transactions or booking)
- academic/scientific questions

Mix:
- 50% near-OOD (still voice-command style but unrelated to SNIPS intents)
- 50% far-OOD (non-assistant-like informational queries)

Output format:
- one sentence per line
- no numbering
- no explanations
"""

    completion = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{"role": "user", "content": prompt}]
    )

    lines = completion.choices[0].message.content.strip().split('\n')

    cleaned = []
    for l in lines:
        l = l.strip()
        if 3 <= len(l.split()) <= 12:
            cleaned.append(l)

    return cleaned[:n]

In [5]:
# ==========================================
# ŁADOWANIE I ŁĄCZENIE DANYCH (7 klas + 1)
# ==========================================
print("--- Pobieranie zbioru SNIPS (7 klas) ---")
raw_ds = load_dataset("DeepPavlov/snips", "default")
train_df = pd.DataFrame(raw_ds['train'])
test_df = pd.DataFrame(raw_ds['test'])
snips_df = pd.concat([train_df, test_df], ignore_index=True) # Zawiera klasy 0-6

possible_text_cols = ['query', 'utterance', 'text', 'sentence']
for col in possible_text_cols:
    if col in snips_df.columns:
        snips_df = snips_df.rename(columns={col: 'text'})
        break

# Pobieranie Unknown
unknown_texts = generate_unknown_data(NUM_OOD_SAMPLES)
OOD_CLASS_IDX = 7
unknown_df = pd.DataFrame({'text': unknown_texts, 'label': OOD_CLASS_IDX})

# Łączenie wszystkiego w jeden dataset
full_df = pd.concat([snips_df[['text', 'label']], unknown_df], ignore_index=True)
full_df.to_csv(f"{SAVE_PATH}/final_dataset_debug.csv", index=False)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def tokenize_fn(batch):
    return tokenizer(batch["text"], padding="max_length", truncation=True)

--- Pobieranie zbioru SNIPS (7 klas) ---

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/366k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/13084 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1400 [00:00<?, ? examples/s]

--- Generowanie 1750 przykładów klasy Unknown przez Groq ---

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [ ]:
# ==========================================
# WALIDACJA LEAVE-TWO-OUT (5 FOLDS)
# ==========================================


FOLDS_CONFIG = [
    {"ood": [5, 6], "name": "Kino"},
    {"ood": [3, 0], "name": "Muzyka"},
    {"ood": [2, 1], "name": "Usługi"},
    {"ood": [4, 5], "name": "Twórczość"},
    {"ood": [6, 1], "name": "Mieszany"}
]


fold_results = []

for fold_idx, config in enumerate(FOLDS_CONFIG):
    ood_classes = config["ood"]
    id_classes = [c for c in range(7) if c not in ood_classes]

    print(f"\n>>> Rozpoczynanie Fałdu {fold_idx+1}/5: {config['name']}")
    print(f">>> Klasy ID (treningowe): {id_classes}")
    print(f">>> Klasy ukryte (OOD): {ood_classes}")


    # 1. Separujemy dane na ID (znane), OOD (ukryte) i Syntetyczne (Unknown)
    id_df_full = full_df[full_df['label'].isin(id_classes)].copy()
    ood_df_full = full_df[full_df['label'].isin(ood_classes)].copy()
    unknown_df_full = full_df[full_df['label'] == 7].copy()

    # 2. Dzielimy dane ID na próbki treningowe i testowe (np. 80/20)
    # Dzięki stratify zachowujemy proporcje podklas w treningu
    train_id, test_id = train_test_split(
        id_df_full, test_size=0.2, stratify=id_df_full['label'], random_state=42
    )


    # 4. SKŁADANIE FINALNYCH ZBIORÓW:
    # Trening: Widziane klasy ID + próbki Syntetyczne
    train_df_fold = pd.concat([train_id, unknown_df_full]).sample(frac=1, random_state=42)

    # Test: Niewidziane próbki ID + CAŁE ukryte OOD
    test_df_fold = pd.concat([test_id, ood_df_full]).sample(frac=1, random_state=42)

    mapping = {old_id: new_id for new_id, old_id in enumerate(id_classes)}
    mapping[7] = 5 # Klasa syntetyczna zawsze na ostatni indeks (5)

    train_fold_mapped = train_df_fold.copy()
    train_fold_mapped['mapped_label'] = train_fold_mapped['label'].map(mapping)

    train_ds = Dataset.from_pandas(train_fold_mapped[['text', 'mapped_label']].rename(columns={'mapped_label': 'label'})).map(tokenize_fn, batched=True)
    test_ds = Dataset.from_pandas(test_df_fold).map(tokenize_fn, batched=True)

    # Inicjalizacja modelu
    model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=6)

    training_args = TrainingArguments(
        output_dir=f"./temp_fold",
        num_train_epochs=3,
        per_device_train_batch_size=32,
        eval_strategy="no",
        save_strategy="no",
        logging_steps=100,
        report_to="none",
        fp16=True
    )

    trainer = Trainer(model=model, args=training_args, train_dataset=train_ds)
    trainer.train()

    # Przygotowanie do predykcji
    test_ds_for_predict = test_ds.remove_columns(["label"])

    # =========================
    # PREDYKCJA
    # =========================
    preds = trainer.predict(test_ds_for_predict)
    logits = preds.predictions
    true_labels = test_df_fold['label'].values

    probs = torch.softmax(torch.tensor(logits), dim=-1).numpy()
    pred_labels_mapped = np.argmax(probs, axis=1)
    ood_scores = probs[:, 5]

    # =========================
    # METRYKI OOD
    # =========================
    eval_mask = (true_labels != 7)
    y_true_binary = np.array([1 if l in ood_classes else 0 for l in true_labels[eval_mask]])
    y_scores = ood_scores[eval_mask]

    auroc = roc_auc_score(y_true_binary, y_scores)
    precision, recall, _ = precision_recall_curve(y_true_binary, y_scores)
    aupr = auc(recall, precision)

    fpr, tpr, thresholds = roc_curve(y_true_binary, y_scores)
    idx_95 = np.argmin(np.abs(tpr - 0.95))
    fpr95 = fpr[idx_95]

    # =========================
    # ZAPIS
    # =========================
    fold_df = pd.DataFrame({
        "text": test_df_fold["text"].values,
        "true_label_original": true_labels,
        "pred_label_mapped": pred_labels_mapped,
        "is_ood_true": [1 if l in ood_classes else 0 for l in true_labels],
        "ood_score": ood_scores,
        "fold": fold_idx + 1,
        "scenario": config['name']
    })

    fold_df.to_csv(f"{SAVE_PATH}/fold_{fold_idx+1}_predictions_exp3.csv", index=False)

    res = {
        "fold": fold_idx + 1,
        "scenario": config['name'],
        "auroc": auroc,
        "aupr": aupr,
        "fpr95": fpr95
    }
    fold_results.append(res)

    print(f"Fold {fold_idx+1} zakończony. AUROC (Real OOD): {auroc:.4f}")

    # Czyszczenie pamięci
    del model
    del trainer
    torch.cuda.empty_cache()

>>> Rozpoczynanie Fałdu 1/5: Kino
>>> Klasy ID (treningowe): [0, 1, 2, 3, 4]
>>> Klasy ukryte (OOD): [5, 6]

Map:   0%|          | 0/8479 [00:00<?, ? examples/s]

Map:   0%|          | 0/6188 [00:00<?, ? examples/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Fold 1 zakończony. AUROC (Real OOD): 0.9506

>>> Rozpoczynanie Fałdu 2/5: Muzyka
>>> Klasy ID (treningowe): [1, 2, 4, 5, 6]
>>> Klasy ukryte (OOD): [3, 0]

Map:   0%|          | 0/8456 [00:00<?, ? examples/s]

Map:   0%|          | 0/6211 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Fold 2 zakończony. AUROC (Real OOD): 0.6119

>>> Rozpoczynanie Fałdu 3/5: Usługi
>>> Klasy ID (treningowe): [0, 3, 4, 5, 6]
>>> Klasy ukryte (OOD): [2, 1]

Map:   0%|          | 0/8431 [00:00<?, ? examples/s]

Map:   0%|          | 0/6236 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Fold 3 zakończony. AUROC (Real OOD): 0.9317

>>> Rozpoczynanie Fałdu 4/5: Twórczość
>>> Klasy ID (treningowe): [0, 1, 2, 3, 6]
>>> Klasy ukryte (OOD): [4, 5]

Map:   0%|          | 0/8482 [00:00<?, ? examples/s]

Map:   0%|          | 0/6185 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Fold 4 zakończony. AUROC (Real OOD): 0.9365

>>> Rozpoczynanie Fałdu 5/5: Mieszany
>>> Klasy ID (treningowe): [0, 2, 3, 4, 5]
>>> Klasy ukryte (OOD): [6, 1]

Map:   0%|          | 0/8464 [00:00<?, ? examples/s]

Map:   0%|          | 0/6203 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Fold 5 zakończony. AUROC (Real OOD): 0.7797

In [ ]:
# ==========================================
# PODSUMOWANIE I EKSPORT
# ==========================================
# Tworzymy główny DataFrame z wynikami wszystkich foldów
df_res = pd.DataFrame(fold_results)

# 1. ZAPIS WYNIKÓW SZCZEGÓŁOWYCH (Każdy fold/scenariusz osobno)
detailed_path = f"{SAVE_PATH}/wyniki_szczegolowe_per_fold_exp3.csv"
df_res.to_csv(detailed_path, index=False)
print(f"Zapisano wyniki szczegółowe dla każdego foldu w: {detailed_path}")

# 2. ZAPIS PODSUMOWANIA STATYSTYCZNEGO (Średnia + Odchylenie)
summary = {
    "Metric": ["AUROC", "AUPR", "FPR95"],
    "Mean": [df_res["auroc"].mean(), df_res["aupr"].mean(), df_res["fpr95"].mean()],
    "Std": [df_res["auroc"].std(), df_res["aupr"].std(), df_res["fpr95"].std()]
}
df_summary = pd.DataFrame(summary)
summary_path = f"{SAVE_PATH}/podsumowanie_statystyczne_exp3.csv"
df_summary.to_csv(summary_path, index=False)
print(f"Zapisano podsumowanie statystyczne w: {summary_path}")

# ==========================================
# WYŚWIETLENIE WYNIKÓW W KONSOLI
# ==========================================
print("\n" + "="*30)
print("RAPORT KOŃCOWY EKSPERYMENTU LEAVE 2 OUT")
print("="*30)
print("\n--- WYNIKI PER SCENARIUSZ (FOLD) ---")
print(df_res[["fold", "scenario", "auroc", "aupr", "fpr95"]].to_string(index=False))

print("\n--- ŚREDNIA I ODCHYLENIE (ŁĄCZNIE) ---")
print(df_summary.to_string(index=False))

Zapisano wyniki szczegółowe dla każdego foldu w: /content/drive/MyDrive/SNIPS_OOD_Project/wyniki_szczegolowe_per_fold_exp3.csv
Zapisano podsumowanie statystyczne w: /content/drive/MyDrive/SNIPS_OOD_Project/podsumowanie_statystyczne_exp3.csv

==============================
RAPORT KOŃCOWY EKSPERYMENTU LEAVE 2 OUT
==============================

--- WYNIKI PER SCENARIUSZ (FOLD) ---
 fold  scenario    auroc     aupr    fpr95
    1      Kino 0.950558 0.978660 0.386024
    2    Muzyka 0.611861 0.769658 0.907685
    3    Usługi 0.931711 0.958012 0.304896
    4 Twórczość 0.936531 0.974963 0.676145
    5  Mieszany 0.779674 0.903505 0.921294

--- ŚREDNIA I ODCHYLENIE (ŁĄCZNIE) ---
Metric     Mean      Std
 AUROC 0.842067 0.146303
  AUPR 0.916960 0.087657
 FPR95 0.639209 0.286742

In [ ]:
from sklearn.model_selection import train_test_split
import torch
import numpy as np
import pandas as pd
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import roc_auc_score, precision_recall_curve, auc

# ==========================================
# WALIDACJA LEAVE-ONE-OUT (7 FOLDS)
# ==========================================

NUM_REAL_CLASSES = 7  # Klasy od 0 do 6
fold_results = []

for ood_class_idx in range(NUM_REAL_CLASSES):
    # Definicja klas dla tego foldu
    ood_classes = [ood_class_idx]
    id_classes = [c for c in range(NUM_REAL_CLASSES) if c != ood_class_idx]

    # Nazwa scenariusza na podstawie wyrzuconej klasy
    scenario_name = f"OOD_Class_{ood_class_idx}"

    print(f"\n>>> Rozpoczynanie Fałdu {ood_class_idx + 1}/{NUM_REAL_CLASSES}: {scenario_name}")
    print(f">>> Klasy ID (treningowe): {id_classes}")
    print(f">>> Klasa ukryta (OOD): {ood_classes}")

    # 1. Separujemy dane
    id_df_full = full_df[full_df['label'].isin(id_classes)].copy()
    ood_df_full = full_df[full_df['label'].isin(ood_classes)].copy()
    unknown_df_full = full_df[full_df['label'] == 7].copy()

    # 2. Split ID na train/test
    train_id, test_id = train_test_split(
        id_df_full, test_size=0.2, stratify=id_df_full['label'], random_state=42
    )

    # 3. Składanie zbiorów
    # Trening: 6 klas ID + klasa syntetyczna (7)
    train_df_fold = pd.concat([train_id, unknown_df_full]).sample(frac=1, random_state=42)
    # Test: Reszta z 6 klas ID + CAŁA wyrzucona klasa OOD
    test_df_fold = pd.concat([test_id, ood_df_full]).sample(frac=1, random_state=42)

    # 4. Mapowanie etykiet (0-5 dla ID, 6 dla syntetycznej)
    mapping = {old_id: new_id for new_id, old_id in enumerate(id_classes)}
    mapping[7] = len(id_classes)  # Klasa syntetyczna ląduje na indeksie 6

    train_fold_mapped = train_df_fold.copy()
    train_fold_mapped['mapped_label'] = train_fold_mapped['label'].map(mapping)

    # Przygotowanie Datasetów
    train_ds = Dataset.from_pandas(
        train_fold_mapped[['text', 'mapped_label']].rename(columns={'mapped_label': 'label'})
    ).map(tokenize_fn, batched=True)

    test_ds = Dataset.from_pandas(test_df_fold).map(tokenize_fn, batched=True)

    # 5. Inicjalizacja modelu (num_labels = 6 ID + 1 Syntetyczna = 7)
    model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=len(id_classes) + 1)

    training_args = TrainingArguments(
        output_dir=f"./temp_fold_loo",
        num_train_epochs=3,
        per_device_train_batch_size=32,
        eval_strategy="no",
        save_strategy="no",
        logging_steps=100,
        report_to="none",
        fp16=True
    )

    trainer = Trainer(model=model, args=training_args, train_dataset=train_ds)
    trainer.train()

    # 6. Predykcja
    test_ds_for_predict = test_ds.remove_columns(["label"])
    preds = trainer.predict(test_ds_for_predict)
    logits = preds.predictions
    true_labels = test_df_fold['label'].values

    probs = torch.softmax(torch.tensor(logits), dim=-1).numpy()
    pred_labels_mapped = np.argmax(probs, axis=1)

    # Wynik OOD to prawdopodobieństwo klasy "Unknown" (ostatni indeks)
    ood_scores = probs[:, len(id_classes)]

    # 7. Metryki (wykluczamy syntetyczne z testu, jeśli by tam były -
    # w tym kodzie test_id ich nie ma, ale zachowujemy maskę dla bezpieczeństwa)
    eval_mask = (true_labels != 7)
    y_true_binary = np.array([1 if l in ood_classes else 0 for l in true_labels[eval_mask]])
    y_scores = ood_scores[eval_mask]

    auroc = roc_auc_score(y_true_binary, y_scores)
    precision, recall, _ = precision_recall_curve(y_true_binary, y_scores)
    aupr = auc(recall, precision)

    fpr, tpr, thresholds = roc_curve(y_true_binary, y_scores)
    idx_95 = np.argmin(np.abs(tpr - 0.95))
    fpr95 = fpr[idx_95]

    # 8. Zapis wyników cząstkowych
    fold_df = pd.DataFrame({
        "text": test_df_fold["text"].values,
        "true_label_original": true_labels,
        "pred_label_mapped": pred_labels_mapped,
        "is_ood_true": [1 if l in ood_classes else 0 for l in true_labels],
        "ood_score": ood_scores,
        "fold": ood_class_idx + 1,
        "scenario": scenario_name
    })
    fold_df.to_csv(f"{SAVE_PATH}/fold_loo_{ood_class_idx+1}_predictions.csv", index=False)

    res = {
        "fold": ood_class_idx + 1,
        "scenario": scenario_name,
        "auroc": auroc,
        "aupr": aupr,
        "fpr95": fpr95
    }
    fold_results.append(res)

    print(f"Fold {ood_class_idx+1} zakończony. Klasa OOD: {ood_class_idx} | AUROC: {auroc:.4f}")

    # Czyszczenie
    del model
    del trainer
    torch.cuda.empty_cache()

>>> Rozpoczynanie Fałdu 1/7: OOD_Class_0
>>> Klasy ID (treningowe): [1, 2, 3, 4, 5, 6]
>>> Klasa ukryta (OOD): [0]

Map:   0%|          | 0/10136 [00:00<?, ? examples/s]

Map:   0%|          | 0/4531 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Fold 1 zakończony. Klasa OOD: 0 | AUROC: 0.3100

>>> Rozpoczynanie Fałdu 2/7: OOD_Class_1
>>> Klasy ID (treningowe): [0, 2, 3, 4, 5, 6]
>>> Klasa ukryta (OOD): [1]

Map:   0%|          | 0/10111 [00:00<?, ? examples/s]

Map:   0%|          | 0/4556 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Fold 2 zakończony. Klasa OOD: 1 | AUROC: 0.9059

>>> Rozpoczynanie Fałdu 3/7: OOD_Class_2
>>> Klasy ID (treningowe): [0, 1, 3, 4, 5, 6]
>>> Klasa ukryta (OOD): [2]

Map:   0%|          | 0/10090 [00:00<?, ? examples/s]

Map:   0%|          | 0/4577 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Fold 3 zakończony. Klasa OOD: 2 | AUROC: 0.9361

>>> Rozpoczynanie Fałdu 4/7: OOD_Class_3
>>> Klasy ID (treningowe): [0, 1, 2, 4, 5, 6]
>>> Klasa ukryta (OOD): [3]

Map:   0%|          | 0/10090 [00:00<?, ? examples/s]

Map:   0%|          | 0/4577 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Fold 4 zakończony. Klasa OOD: 3 | AUROC: 0.8329

>>> Rozpoczynanie Fałdu 5/7: OOD_Class_4
>>> Klasy ID (treningowe): [0, 1, 2, 3, 5, 6]
>>> Klasa ukryta (OOD): [4]

Map:   0%|          | 0/10125 [00:00<?, ? examples/s]

Map:   0%|          | 0/4542 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Fold 5 zakończony. Klasa OOD: 4 | AUROC: 0.9412

>>> Rozpoczynanie Fałdu 6/7: OOD_Class_5
>>> Klasy ID (treningowe): [0, 1, 2, 3, 4, 6]
>>> Klasa ukryta (OOD): [5]

Map:   0%|          | 0/10127 [00:00<?, ? examples/s]

Map:   0%|          | 0/4540 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Fold 6 zakończony. Klasa OOD: 5 | AUROC: 0.8618

>>> Rozpoczynanie Fałdu 7/7: OOD_Class_6
>>> Klasy ID (treningowe): [0, 1, 2, 3, 4, 5]
>>> Klasa ukryta (OOD): [6]

Map:   0%|          | 0/10123 [00:00<?, ? examples/s]

Map:   0%|          | 0/4544 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Fold 7 zakończony. Klasa OOD: 6 | AUROC: 0.7498

In [ ]:
# ==========================================
# PODSUMOWANIE I EKSPORT (LOO)
# ==========================================
df_res = pd.DataFrame(fold_results)

# Zapis wyników
df_res.to_csv(f"{SAVE_PATH}/wyniki_loo_per_class.csv", index=False)

summary = {
    "Metric": ["AUROC", "AUPR", "FPR95"],
    "Mean": [df_res["auroc"].mean(), df_res["aupr"].mean(), df_res["fpr95"].mean()],
    "Std": [df_res["auroc"].std(), df_res["aupr"].std(), df_res["fpr95"].std()]
}
df_summary = pd.DataFrame(summary)
df_summary.to_csv(f"{SAVE_PATH}/podsumowanie_statystyczne_loo.csv", index=False)

print("\n--- RAPORT KOŃCOWY LEAVE-ONE-OUT ---")
print(df_res[["fold", "scenario", "auroc", "fpr95"]].to_string(index=False))
print("\n--- STATYSTYKI ŁĄCZNE ---")
print(df_summary.to_string(index=False))

--- RAPORT KOŃCOWY LEAVE-ONE-OUT ---
 fold    scenario    auroc    fpr95
    1 OOD_Class_0 0.309953 0.971073
    2 OOD_Class_1 0.905859 0.613774
    3 OOD_Class_2 0.936103 0.374647
    4 OOD_Class_3 0.832857 0.605168
    5 OOD_Class_4 0.941221 0.458568
    6 OOD_Class_5 0.861849 0.596943
    7 OOD_Class_6 0.749835 0.894970

--- STATYSTYKI ŁĄCZNE ---
Metric     Mean      Std
 AUROC 0.791097 0.222368
  AUPR 0.815024 0.182020
 FPR95 0.645020 0.216613

In [ ]:
# ==========================================
# EKSPERYMENT "ONE-VS-REST" (ODWRÓCONY)
# ==========================================
# Uczymy na 1 wybranej klasie realnej + klasie Syntetycznej (Unknown).
# Testujemy na reszcie świata (pozostałe 6 klas jako OOD).

fold_results_ovr = []

for target_class_idx in range(NUM_REAL_CLASSES):
    # Definicja ról dla tego foldu
    id_class = [target_class_idx]
    ood_classes = [c for c in range(NUM_REAL_CLASSES) if c != target_class_idx]

    # Nazwa scenariusza dla jasności w logach i plikach
    scenario_name = f"Train_on_class_{target_class_idx}_vs_Rest"

    print(f"\n>>> Rozpoczynanie Eksperymentu Odwróconego {target_class_idx + 1}/7")
    print(f">>> Klasa ID (treningowa): {id_class}")
    print(f">>> Klasy testowane jako OOD: {ood_classes}")

    # 1. Separujemy dane
    id_df_full = full_df[full_df['label'] == target_class_idx].copy()
    ood_df_full = full_df[full_df['label'].isin(ood_classes)].copy()
    unknown_df_full = full_df[full_df['label'] == 7].copy()

    # 2. Split ID na train/test (80/20)
    train_id, test_id = train_test_split(
        id_df_full, test_size=0.2, stratify=id_df_full['label'], random_state=42
    )

    # 3. Składanie finalnych zbiorów dla tego foldu
    # Trening: 1 klasa ID + Syntetyczne (label 7)
    train_df_fold = pd.concat([train_id, unknown_df_full]).sample(frac=1, random_state=42)
    # Test: Próbki testowe ID + WSZYSTKIE pozostałe klasy OOD
    test_df_fold = pd.concat([test_id, ood_df_full]).sample(frac=1, random_state=42)

    # 4. Mapowanie etykiet (0: Znana klasa, 1: Unknown/Syntetyczna)
    mapping = {target_class_idx: 0, 7: 1}

    train_fold_mapped = train_df_fold.copy()
    train_fold_mapped['mapped_label'] = train_fold_mapped['label'].map(mapping)

    # Przygotowanie Datasetów HuggingFace
    train_ds = Dataset.from_pandas(
        train_fold_mapped[['text', 'mapped_label']].rename(columns={'mapped_label': 'label'})
    ).map(tokenize_fn, batched=True)

    test_ds = Dataset.from_pandas(test_df_fold).map(tokenize_fn, batched=True)

    # 5. Inicjalizacja modelu (Problem binarny: Znana vs Syntetyczna)
    model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)

    training_args = TrainingArguments(
        output_dir=f"./temp_fold_ovr",
        num_train_epochs=3,
        per_device_train_batch_size=32,
        eval_strategy="no",
        save_strategy="no",
        logging_steps=100,
        report_to="none",
        fp16=True
    )

    trainer = Trainer(model=model, args=training_args, train_dataset=train_ds)
    trainer.train()

    # 6. Predykcja na zbiorze testowym
    test_ds_for_predict = test_ds.remove_columns(["label"])
    preds = trainer.predict(test_ds_for_predict)
    logits = preds.predictions
    true_labels = test_df_fold['label'].values

    probs = torch.softmax(torch.tensor(logits), dim=-1).numpy()
    pred_labels_mapped = np.argmax(probs, axis=1)

    # Wynik OOD to pewność modelu co do klasy "1" (Unknown)
    ood_scores = probs[:, 1]

    # 7. Obliczanie metryk OOD
    # Chcemy sprawdzić, jak ood_score (prawd. klasy syntetycznej) odróżnia ID od realnego OOD
    y_true_binary = np.array([1 if l in ood_classes else 0 for l in true_labels])
    y_scores = ood_scores

    auroc = roc_auc_score(y_true_binary, y_scores)
    precision, recall, _ = precision_recall_curve(y_true_binary, y_scores)
    aupr = auc(recall, precision)

    fpr, tpr, thresholds = roc_curve(y_true_binary, y_scores)
    idx_95 = np.argmin(np.abs(tpr - 0.95))
    fpr95 = fpr[idx_95]

    # 8. ZAPIS PEŁNEJ INFORMACJI (bez wycinania kolumn)
    fold_df = pd.DataFrame({
        "text": test_df_fold["text"].values,
        "true_label_original": true_labels,
        "pred_label_mapped": pred_labels_mapped,
        "is_ood_true": y_true_binary,
        "ood_score": ood_scores,
        "fold": target_class_idx + 1,
        "scenario": scenario_name,
        "trained_on_id_class": target_class_idx
    })

    # Zapis każdego foldu do osobnego pliku
    fold_df.to_csv(f"{SAVE_PATH}/fold_ovr_{target_class_idx}_predictions_full.csv", index=False)

    # Kolekcjonowanie wyników zbiorczych
    res = {
        "fold": target_class_idx + 1,
        "scenario": scenario_name,
        "trained_on": target_class_idx,
        "auroc": auroc,
        "aupr": aupr,
        "fpr95": fpr95
    }
    fold_results_ovr.append(res)

    print(f"Zakończono: {scenario_name} | AUROC: {auroc:.4f}")

    # Czyszczenie zasobów GPU
    del model
    del trainer
    torch.cuda.empty_cache()

In [ ]:
# ==========================================
# PODSUMOWANIE I EKSPORT WYNIKÓW OVR
# ==========================================
df_res_ovr = pd.DataFrame(fold_results_ovr)

# 1. Zapis wyników szczegółowych dla wszystkich foldów OVR
detailed_path_ovr = f"{SAVE_PATH}/wyniki_szczegolowe_ovr_exp.csv"
df_res_ovr.to_csv(detailed_path_ovr, index=False)

# 2. Zapis podsumowania statystycznego
summary_ovr = {
    "Metric": ["AUROC", "AUPR", "FPR95"],
    "Mean": [df_res_ovr["auroc"].mean(), df_res_ovr["aupr"].mean(), df_res_ovr["fpr95"].mean()],
    "Std": [df_res_ovr["auroc"].std(), df_res_ovr["aupr"].std(), df_res_ovr["fpr95"].std()]
}
df_summary_ovr = pd.DataFrame(summary_ovr)
df_summary_ovr.to_csv(f"{SAVE_PATH}/podsumowanie_statystyczne_ovr.csv", index=False)

print("\n" + "="*30)
print("RAPORT KOŃCOWY ONE-VS-REST")
print("="*30)
print(df_res_ovr[["fold", "trained_on", "auroc", "fpr95"]].to_string(index=False))
print("\n--- ŚREDNIE WYNIKI OVR ---")
print(df_summary_ovr.to_string(index=False))

In [8]:
from sklearn.model_selection import train_test_split
import torch
import numpy as np
import pandas as pd
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import roc_auc_score, precision_recall_curve, auc, roc_curve
from transformers_interpret import SequenceClassificationExplainer

# ==========================================
# WALIDACJA LEAVE-ONE-OUT (7 FOLDS) + XAI DO CSV
# ==========================================

NUM_REAL_CLASSES = 7  # Klasy od 0 do 6
fold_results = []

# NOWOŚĆ: Lista, która zbierze wyniki XAI ze wszystkich fałdów
xai_global_rows = []

for ood_class_idx in range(NUM_REAL_CLASSES):
    ood_classes = [ood_class_idx]
    id_classes = [c for c in range(NUM_REAL_CLASSES) if c != ood_class_idx]
    scenario_name = f"OOD_Class_{ood_class_idx}"

    # 1. Separujemy dane
    id_df_full = full_df[full_df['label'].isin(id_classes)].copy()
    ood_df_full = full_df[full_df['label'].isin(ood_classes)].copy()
    unknown_df_full = full_df[full_df['label'] == 7].copy()

    # 2. Split ID na train/test
    train_id, test_id = train_test_split(
        id_df_full, test_size=0.2, stratify=id_df_full['label'], random_state=42
    )

    # 3. Składanie zbiorów
    train_df_fold = pd.concat([train_id, unknown_df_full]).sample(frac=1, random_state=42)
    test_df_fold = pd.concat([test_id, ood_df_full]).sample(frac=1, random_state=42)

    # 4. Mapowanie etykiet
    mapping = {old_id: new_id for new_id, old_id in enumerate(id_classes)}
    mapping[7] = len(id_classes)

    train_fold_mapped = train_df_fold.copy()
    train_fold_mapped['mapped_label'] = train_fold_mapped['label'].map(mapping)

    train_ds = Dataset.from_pandas(
        train_fold_mapped[['text', 'mapped_label']].rename(columns={'mapped_label': 'label'})
    ).map(tokenize_fn, batched=True)

    test_ds = Dataset.from_pandas(test_df_fold).map(tokenize_fn, batched=True)

    # 5. Inicjalizacja modelu
    model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=len(id_classes) + 1)

    training_args = TrainingArguments(
        output_dir=f"./temp_fold_loo",
        num_train_epochs=3,
        per_device_train_batch_size=32,
        eval_strategy="no",
        save_strategy="no",
        logging_steps=100,
        report_to="none",
        disable_tqdm=True,
        fp16=True
    )

    trainer = Trainer(model=model, args=training_args, train_dataset=train_ds)
    trainer.train()

    # 6. Predykcja
    test_ds_for_predict = test_ds.remove_columns(["label"])
    preds = trainer.predict(test_ds_for_predict)
    logits = preds.predictions
    true_labels = test_df_fold['label'].values

    probs = torch.softmax(torch.tensor(logits), dim=-1).numpy()
    pred_labels_mapped = np.argmax(probs, axis=1)
    ood_scores = probs[:, len(id_classes)]

    # 7. Metryki
    eval_mask = (true_labels != 7)
    y_true_binary = np.array([1 if l in ood_classes else 0 for l in true_labels[eval_mask]])
    y_scores = ood_scores[eval_mask]

    auroc = roc_auc_score(y_true_binary, y_scores)
    precision, recall, _ = precision_recall_curve(y_true_binary, y_scores)
    aupr = auc(recall, precision)

    fpr, tpr, thresholds = roc_curve(y_true_binary, y_scores)
    idx_95 = np.argmin(np.abs(tpr - 0.95))
    fpr95 = fpr[idx_95]

    # 8. Zapis standardowych wyników cząstkowych do CSV
    fold_df = pd.DataFrame({
        "text": test_df_fold["text"].values,
        "true_label_original": true_labels,
        "pred_label_mapped": pred_labels_mapped,
        "is_ood_true": [1 if l in ood_classes else 0 for l in true_labels],
        "ood_score": ood_scores,
        "fold": ood_class_idx + 1,
        "scenario": scenario_name
    })
    fold_df.to_csv(f"{SAVE_PATH}/fold_loo_{ood_class_idx+1}_predictions.csv", index=False)

    fold_results.append({"fold": ood_class_idx + 1, "scenario": scenario_name, "auroc": auroc, "aupr": aupr, "fpr95": fpr95})

    # ==========================================
    # SEKCJA XAI Z EKSTRAKCJĄ DANYCH DO CSV
    # ==========================================
    print(f"\n" + "="*60)
    print(f" GENEROWANIE REPORTU XAI DLA FOLD {ood_class_idx + 1}/{NUM_REAL_CLASSES}")
    print("="*60)

    cls_explainer = SequenceClassificationExplainer(model, tokenizer)
    top_5_indices = np.argsort(ood_scores)[::-1][:5]

    for rank, idx in enumerate(top_5_indices, 1):
        sample_text = test_df_fold.iloc[idx]['text']
        score = ood_scores[idx]

        # Wyjaśnienie przy użyciu zintegrowanych gradientów (indeks klasy OOD)
        word_attributions = cls_explainer(sample_text, index=len(id_classes))

        # Sortowanie tokenów o dodatnim wpływie
        top_tokens = sorted(
            [attr for attr in word_attributions if attr[1] > 0],
            key=lambda x: x[1],
            reverse=True
        )

        # Wyciągamy top 3 triggery dla SNIPS (bezpieczna ekstrakcja na wypadek bardzo krótkich tekstów)
        t1 = top_tokens[0][0] if len(top_tokens) > 0 else None
        w1 = top_tokens[0][1] if len(top_tokens) > 0 else 0.0

        t2 = top_tokens[1][0] if len(top_tokens) > 1 else None
        w2 = top_tokens[1][1] if len(top_tokens) > 1 else 0.0

        t3 = top_tokens[2][0] if len(top_tokens) > 2 else None
        w3 = top_tokens[2][1] if len(top_tokens) > 2 else 0.0

        # Wypisanie kontrolne w konsoli (skrócone do top 3)
        print(f"\n[Top {rank}] Score OOD: {score:.4f} | Tekst: \"{sample_text}\"")
        print(f"   Triggery: 1. {t1} ({w1:.3f}) | 2. {t2} ({w2:.3f}) | 3. {t3} ({w3:.3f})")

        # NOWOŚĆ: Zapisujemy wiersz danych do naszej globalnej listy
        xai_global_rows.append({
            "fold": ood_class_idx + 1,
            "scenario": scenario_name,
            "rank_in_fold": rank,
            "text": sample_text,
            "ood_score": score,
            "trigger_1_token": t1,
            "trigger_1_weight": w1,
            "trigger_2_token": t2,
            "trigger_2_weight": w2,
            "trigger_3_token": t3,
            "trigger_3_weight": w3
        })

    # Czyszczenie pamięci GPU
    del model
    del trainer
    torch.cuda.empty_cache()

# ==========================================
# NOWOŚĆ: GLOBALNY ZAPIS WYNIKÓW XAI DO CSV
# ==========================================
xai_df = pd.DataFrame(xai_global_rows)
xai_df.to_csv(f"{SAVE_PATH}/global_xai_ood_report.csv", index=False)

print("\n" + "="*60)
print(f" KONTROLA KOŃCOWA: Sukces!")
print(f" Globalny raport ważności słów OOD został zapisany w:")
print(f" -> {SAVE_PATH}/global_xai_ood_report.csv")
print("="*60)

Map:   0%|          | 0/10153 [00:00<?, ? examples/s]

Map:   0%|          | 0/4531 [00:00<?, ? examples/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.4521', 'grad_norm': '0.6612', 'learning_rate': '4.481e-05', 'epoch': '0.3145'}
{'loss': '0.07379', 'grad_norm': '0.06958', 'learning_rate': '3.957e-05', 'epoch': '0.6289'}
{'loss': '0.0761', 'grad_norm': '1.649', 'learning_rate': '3.433e-05', 'epoch': '0.9434'}
{'loss': '0.04059', 'grad_norm': '10.07', 'learning_rate': '2.909e-05', 'epoch': '1.258'}
{'loss': '0.03707', 'grad_norm': '4.624', 'learning_rate': '2.385e-05', 'epoch': '1.572'}
{'loss': '0.0244', 'grad_norm': '0.07757', 'learning_rate': '1.861e-05', 'epoch': '1.887'}
{'loss': '0.01384', 'grad_norm': '3.909', 'learning_rate': '1.336e-05', 'epoch': '2.201'}
{'loss': '0.01132', 'grad_norm': '0.01483', 'learning_rate': '8.124e-06', 'epoch': '2.516'}
{'loss': '0.01738', 'grad_norm': '0.01616', 'learning_rate': '2.883e-06', 'epoch': '2.83'}
{'train_runtime': '717.6', 'train_samples_per_second': '42.45', 'train_steps_per_second': '1.329', 'train_loss': '0.07865', 'epoch': '3'}

============================================================
 GENEROWANIE REPORTU XAI DLA FOLD 1/7
============================================================

[Top 1] Score OOD: 0.0148 | Tekst: "Add fuzzy logic to latin dinner"
   Triggery: 1. dinner (0.734) | 2. add (0.196) | 3. fuzzy (0.120)

[Top 2] Score OOD: 0.0105 | Tekst: "add doing all right to string theory"
   Triggery: 1. add (0.054) | 2. doing (0.002) | 3. None (0.000)

[Top 3] Score OOD: 0.0104 | Tekst: "add I’m Only a Man to my flow español"
   Triggery: 1. add (0.257) | 2. a (0.079) | 3. es (0.048)

[Top 4] Score OOD: 0.0092 | Tekst: "Add od mene se odvikavaj to my laundry"
   Triggery: 1. add (0.556) | 2. laundry (0.028) | 3. None (0.000)

[Top 5] Score OOD: 0.0086 | Tekst: "for my té para tres list add cut the world"
   Triggery: 1. for (0.389) | 2. te (0.143) | 3. my (0.036)

Map:   0%|          | 0/10128 [00:00<?, ? examples/s]

Map:   0%|          | 0/4556 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.4937', 'grad_norm': '3.1', 'learning_rate': '4.479e-05', 'epoch': '0.3155'}
{'loss': '0.0798', 'grad_norm': '5.289', 'learning_rate': '3.954e-05', 'epoch': '0.6309'}
{'loss': '0.06491', 'grad_norm': '0.5545', 'learning_rate': '3.428e-05', 'epoch': '0.9464'}
{'loss': '0.03779', 'grad_norm': '0.2059', 'learning_rate': '2.902e-05', 'epoch': '1.262'}
{'loss': '0.03048', 'grad_norm': '0.03512', 'learning_rate': '2.376e-05', 'epoch': '1.577'}
{'loss': '0.02168', 'grad_norm': '0.05068', 'learning_rate': '1.851e-05', 'epoch': '1.893'}
{'loss': '0.01542', 'grad_norm': '1.942', 'learning_rate': '1.325e-05', 'epoch': '2.208'}
{'loss': '0.006656', 'grad_norm': '0.1082', 'learning_rate': '7.992e-06', 'epoch': '2.524'}
{'loss': '0.009787', 'grad_norm': '0.8363', 'learning_rate': '2.734e-06', 'epoch': '2.839'}
{'train_runtime': '703.6', 'train_samples_per_second': '43.19', 'train_steps_per_second': '1.352', 'train_loss': '0.08015', 'epoch': '3'}

============================================================
 GENEROWANIE REPORTU XAI DLA FOLD 2/7
============================================================

[Top 1] Score OOD: 0.5245 | Tekst: "I need a restaurant that has internet access for a party of six"
   Triggery: 1. restaurant (0.938) | 2. that (0.164) | 3. six (0.146)

[Top 2] Score OOD: 0.3118 | Tekst: "Please book a coffeehouse restaurant type room to accommodate gretchen, trisha and amber which serves pastelaria dish"
   Triggery: 1. restaurant (0.554) | 2. room (0.433) | 3. , (0.308)

[Top 3] Score OOD: 0.3118 | Tekst: "Please book a coffeehouse restaurant type room to accommodate gretchen, trisha and amber which serves pastelaria dish"
   Triggery: 1. restaurant (0.554) | 2. room (0.433) | 3. , (0.308)

[Top 4] Score OOD: 0.3109 | Tekst: "I need to book a restaurant that has wifi far from TX for me and my parents"
   Triggery: 1. restaurant (0.834) | 2. wi (0.243) | 3. that (0.200)

[Top 5] Score OOD: 0.2847 | Tekst: "Please book a joint type restaurant room with spa facility to accommodate 8 members"
   Triggery: 1. accommodate (0.795) | 2. spa (0.410) | 3. please (0.323)

Map:   0%|          | 0/10107 [00:00<?, ? examples/s]

Map:   0%|          | 0/4577 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.5095', 'grad_norm': '2.446', 'learning_rate': '4.478e-05', 'epoch': '0.3165'}
{'loss': '0.07517', 'grad_norm': '0.2435', 'learning_rate': '3.95e-05', 'epoch': '0.6329'}
{'loss': '0.05737', 'grad_norm': '2.685', 'learning_rate': '3.423e-05', 'epoch': '0.9494'}
{'loss': '0.04155', 'grad_norm': '1.77', 'learning_rate': '2.896e-05', 'epoch': '1.266'}
{'loss': '0.0262', 'grad_norm': '0.02268', 'learning_rate': '2.368e-05', 'epoch': '1.582'}
{'loss': '0.02712', 'grad_norm': '0.5402', 'learning_rate': '1.841e-05', 'epoch': '1.899'}
{'loss': '0.01579', 'grad_norm': '2.798', 'learning_rate': '1.313e-05', 'epoch': '2.215'}
{'loss': '0.01103', 'grad_norm': '0.01255', 'learning_rate': '7.859e-06', 'epoch': '2.532'}
{'loss': '0.006872', 'grad_norm': '0.0708', 'learning_rate': '2.584e-06', 'epoch': '2.848'}
{'train_runtime': '701.7', 'train_samples_per_second': '43.21', 'train_steps_per_second': '1.351', 'train_loss': '0.08151', 'epoch': '3'}

============================================================
 GENEROWANIE REPORTU XAI DLA FOLD 3/7
============================================================

[Top 1] Score OOD: 0.9705 | Tekst: "What is the cloud coverage in my current place"
   Triggery: 1. cloud (0.849) | 2. current (0.377) | 3. the (0.250)

[Top 2] Score OOD: 0.9553 | Tekst: "What is the forecasted humidity in Ghana for Epiphany"
   Triggery: 1. humidity (0.863) | 2. what (0.384) | 3. the (0.263)

[Top 3] Score OOD: 0.9549 | Tekst: "Tell me the current forecast for Switzerland"
   Triggery: 1. current (0.586) | 2. the (0.542) | 3. forecast (0.426)

[Top 4] Score OOD: 0.9503 | Tekst: "what is the forecast for the current position"
   Triggery: 1. forecast (0.744) | 2. the (0.452) | 3. position (0.253)

[Top 5] Score OOD: 0.9485 | Tekst: "what is the forecast for colder conditions within the same area of this current place"
   Triggery: 1. the (0.642) | 2. this (0.451) | 3. for (0.354)

Map:   0%|          | 0/10107 [00:00<?, ? examples/s]

Map:   0%|          | 0/4577 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.4495', 'grad_norm': '0.682', 'learning_rate': '4.478e-05', 'epoch': '0.3165'}
{'loss': '0.05658', 'grad_norm': '0.9888', 'learning_rate': '3.95e-05', 'epoch': '0.6329'}
{'loss': '0.04795', 'grad_norm': '0.03391', 'learning_rate': '3.423e-05', 'epoch': '0.9494'}
{'loss': '0.0344', 'grad_norm': '2.211', 'learning_rate': '2.896e-05', 'epoch': '1.266'}
{'loss': '0.01759', 'grad_norm': '0.0159', 'learning_rate': '2.368e-05', 'epoch': '1.582'}
{'loss': '0.0252', 'grad_norm': '0.6526', 'learning_rate': '1.841e-05', 'epoch': '1.899'}
{'loss': '0.01439', 'grad_norm': '1.557', 'learning_rate': '1.313e-05', 'epoch': '2.215'}
{'loss': '0.01045', 'grad_norm': '0.01175', 'learning_rate': '7.859e-06', 'epoch': '2.532'}
{'loss': '0.01049', 'grad_norm': '0.03285', 'learning_rate': '2.584e-06', 'epoch': '2.848'}
{'train_runtime': '701.1', 'train_samples_per_second': '43.24', 'train_steps_per_second': '1.352', 'train_loss': '0.07097', 'epoch': '3'}

============================================================
 GENEROWANIE REPORTU XAI DLA FOLD 4/7
============================================================

[Top 1] Score OOD: 0.0173 | Tekst: "Find Business Ethics A European Review ."
   Triggery: 1. ethics (0.697) | 2. . (0.260) | 3. business (0.055)

[Top 2] Score OOD: 0.0039 | Tekst: "Play me Gil Parris 's A Cup Of Coffee, A Sandwich And You"
   Triggery: 1. sandwich (0.181) | 2. par (0.146) | 3. coffee (0.123)

[Top 3] Score OOD: 0.0027 | Tekst: "Play Short Walk On A Long Pier on Slacker"
   Triggery: 1. play (0.414) | 2. None (0.000) | 3. None (0.000)

[Top 4] Score OOD: 0.0026 | Tekst: "I need some Hardcore Hip Hop"
   Triggery: 1. hardcore (0.285) | 2. hop (0.242) | 3. i (0.150)

[Top 5] Score OOD: 0.0023 | Tekst: "Play slow rock music on Vimeo"
   Triggery: 1. vi (0.245) | 2. on (0.089) | 3. None (0.000)

Map:   0%|          | 0/10142 [00:00<?, ? examples/s]

Map:   0%|          | 0/4542 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.529', 'grad_norm': '1.786', 'learning_rate': '4.479e-05', 'epoch': '0.3155'}
{'loss': '0.08631', 'grad_norm': '2.373', 'learning_rate': '3.954e-05', 'epoch': '0.6309'}
{'loss': '0.07362', 'grad_norm': '11.27', 'learning_rate': '3.428e-05', 'epoch': '0.9464'}
{'loss': '0.03982', 'grad_norm': '0.05547', 'learning_rate': '2.902e-05', 'epoch': '1.262'}
{'loss': '0.03426', 'grad_norm': '3.468', 'learning_rate': '2.376e-05', 'epoch': '1.577'}
{'loss': '0.02968', 'grad_norm': '0.2699', 'learning_rate': '1.851e-05', 'epoch': '1.893'}
{'loss': '0.02115', 'grad_norm': '0.1686', 'learning_rate': '1.325e-05', 'epoch': '2.208'}
{'loss': '0.0152', 'grad_norm': '0.0296', 'learning_rate': '7.992e-06', 'epoch': '2.524'}
{'loss': '0.01132', 'grad_norm': '0.01876', 'learning_rate': '2.734e-06', 'epoch': '2.839'}
{'train_runtime': '703.7', 'train_samples_per_second': '43.23', 'train_steps_per_second': '1.351', 'train_loss': '0.08878', 'epoch': '3'}

============================================================
 GENEROWANIE REPORTU XAI DLA FOLD 5/7
============================================================

[Top 1] Score OOD: 0.9845 | Tekst: "Give Physics of the Impossible four points ."
   Triggery: 1. give (0.794) | 2. physics (0.473) | 3. . (0.254)

[Top 2] Score OOD: 0.9725 | Tekst: "I give The Logic of Sense a zero"
   Triggery: 1. logic (0.572) | 2. zero (0.563) | 3. a (0.397)

[Top 3] Score OOD: 0.9705 | Tekst: "I rate The Variation of Animals and Plants under Domestication a value of 0"
   Triggery: 1. the (0.554) | 2. animals (0.446) | 3. under (0.385)

[Top 4] Score OOD: 0.9686 | Tekst: "Rate Renewable Electricity and the Grid one stars out of 6"
   Triggery: 1. rate (0.613) | 2. electricity (0.509) | 3. renewable (0.389)

[Top 5] Score OOD: 0.9535 | Tekst: "For Adaptive Coloration in Animals I give 4 points"
   Triggery: 1. in (0.744) | 2. animals (0.393) | 3. for (0.365)

Map:   0%|          | 0/10144 [00:00<?, ? examples/s]

Map:   0%|          | 0/4540 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.4361', 'grad_norm': '0.1402', 'learning_rate': '4.479e-05', 'epoch': '0.3155'}
{'loss': '0.02654', 'grad_norm': '0.04628', 'learning_rate': '3.954e-05', 'epoch': '0.6309'}
{'loss': '0.01647', 'grad_norm': '0.08974', 'learning_rate': '3.428e-05', 'epoch': '0.9464'}
{'loss': '0.01366', 'grad_norm': '0.01593', 'learning_rate': '2.902e-05', 'epoch': '1.262'}
{'loss': '0.01865', 'grad_norm': '0.5332', 'learning_rate': '2.376e-05', 'epoch': '1.577'}
{'loss': '0.008342', 'grad_norm': '0.01685', 'learning_rate': '1.851e-05', 'epoch': '1.893'}
{'loss': '0.008349', 'grad_norm': '0.05377', 'learning_rate': '1.325e-05', 'epoch': '2.208'}
{'loss': '0.005345', 'grad_norm': '0.02623', 'learning_rate': '7.992e-06', 'epoch': '2.524'}
{'loss': '0.003403', 'grad_norm': '0.05384', 'learning_rate': '2.734e-06', 'epoch': '2.839'}
{'train_runtime': '703.5', 'train_samples_per_second': '43.26', 'train_steps_per_second': '1.352', 'train_loss': '0.05675', 'epoch': '3'}

============================================================
 GENEROWANIE REPORTU XAI DLA FOLD 6/7
============================================================

[Top 1] Score OOD: 0.9943 | Tekst: "I need a novel about Polymer Chemistry ."
   Triggery: 1. about (0.720) | 2. chemistry (0.345) | 3. . (0.337)

[Top 2] Score OOD: 0.9865 | Tekst: "Need the creative work called The Logic of Scientific Discovery"
   Triggery: 1. called (0.793) | 2. the (0.381) | 3. logic (0.272)

[Top 3] Score OOD: 0.9765 | Tekst: "Info on show Natural Language and Linguistic Theory"
   Triggery: 1. info (0.650) | 2. theory (0.446) | 3. linguistic (0.354)

[Top 4] Score OOD: 0.9469 | Tekst: "looking for Liberalism and the Limits of Justice"
   Triggery: 1. looking (0.551) | 2. the (0.367) | 3. for (0.339)

[Top 5] Score OOD: 0.8939 | Tekst: "What is the TV show Journal of Personality and Social Psychology ?"
   Triggery: 1. of (0.598) | 2. tv (0.561) | 3. journal (0.443)

Map:   0%|          | 0/10140 [00:00<?, ? examples/s]

Map:   0%|          | 0/4544 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.456', 'grad_norm': '2.759', 'learning_rate': '4.479e-05', 'epoch': '0.3155'}
{'loss': '0.05225', 'grad_norm': '1.607', 'learning_rate': '3.954e-05', 'epoch': '0.6309'}
{'loss': '0.03819', 'grad_norm': '0.2176', 'learning_rate': '3.428e-05', 'epoch': '0.9464'}
{'loss': '0.0251', 'grad_norm': '0.05872', 'learning_rate': '2.902e-05', 'epoch': '1.262'}
{'loss': '0.01693', 'grad_norm': '0.01896', 'learning_rate': '2.376e-05', 'epoch': '1.577'}
{'loss': '0.02239', 'grad_norm': '0.05125', 'learning_rate': '1.851e-05', 'epoch': '1.893'}
{'loss': '0.01975', 'grad_norm': '0.2053', 'learning_rate': '1.325e-05', 'epoch': '2.208'}
{'loss': '0.006457', 'grad_norm': '0.0146', 'learning_rate': '7.992e-06', 'epoch': '2.524'}
{'loss': '0.0069', 'grad_norm': '0.02489', 'learning_rate': '2.734e-06', 'epoch': '2.839'}
{'train_runtime': '703.2', 'train_samples_per_second': '43.26', 'train_steps_per_second': '1.352', 'train_loss': '0.068', 'epoch': '3'}

============================================================
 GENEROWANIE REPORTU XAI DLA FOLD 7/7
============================================================

[Top 1] Score OOD: 0.9294 | Tekst: "What are the timings for Starship Troopers 2 ?"
   Triggery: 1. ? (0.788) | 2. stars (0.444) | 3. troopers (0.219)

[Top 2] Score OOD: 0.3647 | Tekst: "What time will The Age of Success be showing?"
   Triggery: 1. time (0.729) | 2. ? (0.439) | 3. be (0.301)

[Top 3] Score OOD: 0.3580 | Tekst: "What time is A Battle of Wits starting?"
   Triggery: 1. ? (0.504) | 2. of (0.405) | 3. time (0.363)

[Top 4] Score OOD: 0.1208 | Tekst: "What are the current movie schedules ?"
   Triggery: 1. what (0.646) | 2. schedules (0.634) | 3. current (0.079)

[Top 5] Score OOD: 0.0913 | Tekst: "What are the movie schedules for movies around here ?"
   Triggery: 1. schedules (0.705) | 2. here (0.329) | 3. ? (0.290)

============================================================
 KONTROLA KOŃCOWA: Sukces!
 Globalny raport ważności słów OOD został zapisany w:
 -> /content/drive/MyDrive/SNIPS_OOD_Project/global_xai_ood_report.csv
============================================================